### ISSUE TITLE
Dialer hangs on 3-way call

### ISSUE THREAD

**Issue by oonet** [SimpleMobileTools/Simple-Dialer#103]
When a caller attempts to merge with another call, Simple Dialer hangs up.

This is a bug because callers use the features on their phone. Feature request would be the ability to place 3-way calls.

**Comment by oonet** [comment]
Okay, maybe an *urgent* feature request? :-)

Calls get disconnected when unsuspecting caller uses the 3-way feature on their phone. In other words, the missing feature interferes with the expected usage of someone else's phone.

**Comment by tibbi** [comment]
conference calls arent yet supported, wont be added anytime soon

**Comment by billybobfrank** [comment]
> 
> 
> conference calls arent yet supported, wont be added anytime soon

Just curious, why wont it be added anytime soon?  Difficulty? 

This would be a great feature to have and many thanks for all your apps.

**Comment by tibbi** [comment]
Not sure, I wasnt even researching it yet. There just isnt enough demand for it to work on.

**Comment by k3tan172** [comment]
I'd like to voice my demand for conference calls. Would be much appreciated.
Thanks for all the apps you create.
