### ISSUE TITLE
[Dual sim] Cannot choose which sim to call from

### ISSUE THREAD

**Issue by rEnr3n** [SimpleMobileTools/Simple-Dialer#107]
I am on a dual sim phone. The stock app has two call buttons. This app has only one. Pressing the call button does nothing.

**Comment by rEnr3n** [comment]
> Have you set the app as the default app for handling calls?

It is set as default app. 

> What app version are you using?

Simple Dialer v5.5.1

I'm using Android v6.0.1

**Comment by phenax** [comment]
+1 same problem here

Version: 5.5.1

**Comment by tibbi** [comment]
it works fine to me, dont you have a default SIM set up in your device settings?

**Comment by rEnr3n** [comment]
There are 3 options in `Dual SIM calling`.

First is `Smart`. It shows 2 call buttons.
> System will intelligently recommend a SIM card based on your previous call patterns.

The other two options is `Simple (defualt SIM X)`. It shows 1 call button.
> Use SIM X as default card. Touch and hold the call icon and slide left of right to switch default SIMs.

I tried both of them and I get the same issue. App version tested at this time is v5.5.4. I don't see this issue on Android 10 however.

**Comment by tibbi** [comment]
some sim card improvements will be added in 5.6.0
