### ISSUE TITLE
feature request: dialpad search function

### ISSUE THREAD

**Issue by Rik44444** [SimpleMobileTools/Simple-Dialer#108]
feature request for adding the option that when you type numbers on the dialpad, the dialer searches your contacts and gives contacts matching A) the numbers and B) the letters corresponding to those numbers. Eg typing 7-4-5 would give you all contacts with 745 in the phone number and also for example "Rik"

Plus an option in the settings to launch the dialpad upon starting the app (i've been searching endlessly for an open source app that can do this!)

**Comment by tibbi** [comment]
it should already search letters too, are you sure it doesnt work?

**Comment by Rik44444** [comment]
you're right, sorry i have a weird phone (jelly), the search results did not show. I tried it on another phone and the results show fine there. So hereby feature request (small bit of work and a great extra!!) to have the option to open the dialpad by default when the app opens.

**Comment by tibbi** [comment]
create a new issue for that though, lets not mix multiple things together

**Comment by Rik44444** [comment]
ok, did so here: https://github.com/SimpleMobileTools/Simple-Dialer/issues/110
