### ISSUE TITLE
feature request: option in settings to open dialpad by default upon opening app

### ISSUE THREAD

**Issue by Rik44444** [SimpleMobileTools/Simple-Dialer#110]
feature request (small bit of work and a great extra!!) to have an option in the settings to "open the dialpad by default when the app opens" 
(i've been searching endlessly for an open source app that can do this!)

**Comment by ernzem** [comment]
+1 for having "open the dialpad by default when the app opens" feature. That would greatly improve productivity for those who rely on T9 search.

**Comment by tibbi** [comment]
will be added in 5.8.1
