### ISSUE TITLE
[Feature Request] Add more options to the call UI

### ISSUE THREAD

**Issue by UX0l0l** [SimpleMobileTools/Simple-Dialer#111]
So, this is one of the main reasons why I don't use this app. when I call someone, I only have the speaker on/off option, the mute on/off option, and the keypad option. On other call UIs like the default one on my phone, there's a button to add others to the call, and a completely different UI for when u actually call someone else and start a conference call with multiple people, so u can do things like merge calls, split calls again, switch between them, end a call and not the other, etc.

![Screenshot_20201004-143609_Call_1](https://user-images.githubusercontent.com/47756363/95015093-c7daf580-0653-11eb-8dba-90179bec3545.jpg)
![Screenshot_20201004-144041_Call_1](https://user-images.githubusercontent.com/47756363/95015096-c9a4b900-0653-11eb-9ac4-c65e69a3202b.jpg)
![Screenshot_20201004-144535_Call_1](https://user-images.githubusercontent.com/47756363/95015097-ca3d4f80-0653-11eb-9866-441250fb68aa.jpg)

here are some screenshots from my OEM dialer app that show this feature in action.

I hope you guys add this, it's the only reason I don't use this app as a daily driver.

**Comment by tibbi** [comment]
adding conference call support is on the roadmap, but it likely wont be added anytime soon. Ill close this as it is already reported.
