### ISSUE TITLE
[Feature Request] Import/Export blocked numbers

### ISSUE THREAD

**Issue by TheFrenchGhosty** [SimpleMobileTools/Simple-Dialer#113]
I curently have dozens of blocked numbers, I curently manage it like I manage my contacts, I add them all to a CSV sheet.

It would be really nice to be able to import/export them directly, if possible in CSV, otherwise any format is fine.

**Comment by gsantner** [comment]
What about a different suggestion, general settings import/export (i.e. backup of prefs.xml), that also covers blocked

**Comment by tibbi** [comment]
will be added in 5.8.1

**Comment by TheFrenchGhosty** [comment]
@tibbi Amazing! Thanks!
