### ISSUE TITLE
Show full history of calls

### ISSUE THREAD

**Issue by tarbib** [SimpleMobileTools/Simple-Dialer#115]
Hello, 

When I have many calls for the same phone number, there is a number in between brackets and the time and duration of the last call below.

i.e : Barack Obama (3) 
20.10 00:26

Is there a way to have time details of the 3 different calls ? Not only the time and duration of the last one.

Thanks

**Comment by tarbib** [comment]
Follow up : by disabling the setting "group subsequent calls with the same number at the call log" we can somehow have the full history.

What I would find nice : when the above mentioned setting is enabled, I click on on a grouped entry of the call log it displays all the logs linked to this entry.

**Comment by genodeftest** [comment]
Different idea:
When grouped, show it in a format like this:
> Barack Obama (3)
> 20.10. 00:26
> 20.10. 00:05
> 21.10. 00:49

In other words: When grouped, show contact name and photo only once but show the other infos (SIM card, incoming or outgoing call, time, duration) per call.

This would be more compact than with _Group subsequent calls with the same number at the call log_ enabled but still provide all the info as if it were disabled.

**Comment by tibbi** [comment]
an initial implementation of showing call details will be added in 5.6.0, some other improvements in the future

**Comment by genodeftest** [comment]
Thanks! The changes in 5.6.0 help working with the grouped mode!
