### ISSUE TITLE
Sometimes call continues when app is closed.

### ISSUE THREAD

**Issue by Skaalgard** [SimpleMobileTools/Simple-Dialer#116]
Sometimes when I accidentally close the app during a call, the call continues in the background but I have absolutely no way to control it. Opening the app again does not allow controlling the call or hanging up. This behavior is very inconsistent and doesn't happen all the time. It should stay open at least in a notification at all times so the call can be controlled at all times.

**Comment by tibbi** [comment]
What app version are you using?

**Comment by Skaalgard** [comment]
5.4.0

**Comment by tibbi** [comment]
upgrade to 5.5.1 please, the call ends there if it is backgrounded
