### ISSUE TITLE
View/Edit contact by long-pressing

### ISSUE THREAD

**Issue by ltGuillaume** [SimpleMobileTools/Simple-Dialer#120]
1. When you long-press a contact entry anywhere in the dialer, there is no button to view/edit the contact in the default contacts app.
2. When you long-press an entry in the call history, there's a button to add the number to a contact, even though it's already added. There should be a button to view/edit the contact instead (opening the default contacts app).

**Comment by tibbi** [comment]
View Contact Details will be added at the top menu from 5.6.0

**Comment by ltGuillaume** [comment]
Great! Thank you 🙂
