### ISSUE TITLE
When choosing a custom background color the color slider moves by itself

### ISSUE THREAD

**Issue by azat11** [SimpleMobileTools/Simple-Dialer#122]
When I'm trying to choose a color by moving my finger in the color field, the slider on the right moves off the color I chose into some other color.

Android 6.0.1
App version 5.5.3

**Comment by tibbi** [comment]
that affects all apps, not just this one. So it should be reported at the General Discussion. It isnt really a big issue though so dont really expect having it fixed soon. Thanks

**Comment by azat11** [comment]
> 
> 
> that affects all apps, not just this one. So it should be reported at the General Discussion. It isnt really a big issue though so dont really expect having it fixed soon. Thanks

Should I copy this to the general discussion or is it already there somewhere?? Sorry for bothering you with this question.

**Comment by tibbi** [comment]
you can report it there
