### ISSUE TITLE
Phone rings when additional call arrives during call, but no interaction possible

### ISSUE THREAD

**Issue by otizonaizit** [SimpleMobileTools/Simple-Dialer#126]
When I am in a call and a second call arrives, my phone rings and I get a notification that I have a second call, but I can't see who is calling, I can't refuse the second call, I basicaly have no other option that listening to the phone ringing while in the call. Even if I hang on the first call, I can not pick up the second one.
I understand that conference calls are not planned at the moment, but there may be an easier way to at least show who the second caller is and have an option of refusing the call, or at least to silence the ring tone.

Thank you for this dialer, by the way, I really appreciate your efforts with the simple apps suite :-)

**Comment by jcw0411** [comment]
I have this issue too. I put this on about 200 phones but I have a few of the users reporting the same issue. I haven't been able to consistently replicate the issue or figure out what might be causing it.

If it's of use, I have an almost working version which implements conference calls (it was necessary for these users to have that) and I will be happy to submit once I get one issue ironed out.

But this second call with no interaction alludes me.

**Comment by asadzoobiapps** [comment]
Hi @jcw0411 i want call merging option in this dialer

**Comment by tibbi** [comment]
should be fixed already
