### ISSUE TITLE
Enable/disable use proximity sensor

### ISSUE THREAD

**Issue by bac1** [SimpleMobileTools/Simple-Dialer#128]
Please add the setting for using proximity sensor (use / not use). It is not convenient to use the application if sensor is glued.

**Comment by tibbi** [comment]
it isnt really on the roadmap, I dont want to spoil the UI with such buttons

**Comment by bac1** [comment]
@tibbi  One extra line in SettingsActivity will mess up the interface?

**Comment by tibbi** [comment]
if I added one extra line for everyones edge case request, it would be really crowded already

**Comment by newsch** [comment]
For what it's worth, a relative of mine has issues with their proximity sensor and their screen is always off whenever they're in a call. I don't want to go through rooting their phone and disabling the sensor directly, ideally they could just turn off the feature in their dialer app. It seems like older versions of the stock aosp dialer used to allow you to disable the proximity sensor locking for calls, but I haven't found any maintained and non-sketchy dialer apps that allow it.
@tibbi I understand your reluctance to add more niche features, but I do think this is would be a useful addition that would resolve a pain point I've seen come up in several forums.
I don't have much experience with Android apps, but I've been looking through the code and I'd be happy to start a PR if you'd like.
Either way, I really appreciate this project of yours and the relative openness of the android platform that allows users to swap out core features and us to have discussions like this.

**Comment by tibbi** [comment]
it would be easy to do, I just dont see demand for it. Might be added in the future once the app grows further.

**Comment by newsch** [comment]
Alright, well thank you for considering it. I will try to make a patch for my relative.
