### ISSUE TITLE
Feature Request: Per-Contact Notification Tones for Message and Call

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/Simple-Dialer#13]
I'd love to see the ability to set custom Notification Tones per contact for Text/Call events to help differentiate each contact from one another.

**Comment by e-t-l** [comment]
As described in [#528](https://github.com/SimpleMobileTools/Simple-Contacts/issues/528#issuecomment-636240056), it really does seem like this functionality would be more appropriate in the Simple Contacts app, seeing as contact-specific ringtones are necessarily a contact-dependent function.

**Comment by tibbi** [comment]
ye, it has been added in Simple Contacts as Simple Dialer's purpose is not editing contacts

**Comment by e-t-l** [comment]
That's good to hear. Was it already added? I have Simple Contacts installed and there's no option for it as of v16.4.3

**Comment by tibbi** [comment]
enable "Ringtone" customization at the app settings -> Manage shown contact fields
