### ISSUE TITLE
Replace Contrast icon

### ISSUE THREAD

**Issue by Github-com-foss** [SimpleMobileTools/Simple-Dialer#133]
Pls replace icon,(now) its look like old (gingerbread,ics) change colorful contrast color, dual tone shade or gradient colors. implement in simple (Message,dialer and contacts )

![images](https://user-images.githubusercontent.com/75672019/102580035-c766dc80-4123-11eb-9c97-a04ce24d391f.jpeg)
![Screenshot](https://user-images.githubusercontent.com/75672019/102580037-c930a000-4123-11eb-83cb-12fdf5674e64.jpg)

**Comment by tibbi** [comment]
as described in your first issue, this isnt on the roadmap
