### ISSUE TITLE
Missed Calls Bug

### ISSUE THREAD

**Issue by r00t34** [SimpleMobileTools/Simple-Dialer#134]
Hi all,

Hope you are well. I replaced "all" stock apps with SimpleMobileTools and i am happy with this.

Let me explain my problem with a scenario.

15:54 and 16:40 missed call received. There are 2 missed calls. I unlocked my phone on 17:05 and saw 2 missed call on notification shade (bar). When i tapped to that notification there is no response. It is not forwarding to call details to me. Just notification is disappearing.

Second issue: When i reboot my phone 15:54 and 16:40 missed call notification is still on notification shade as like new notification.

Could you please help me about these issues?

Thanks in advance.

Kind Regards.

**Comment by tibbi** [comment]
those notifications are handled by the system, not Simple Dialer. It still relies on the system in some way.

**Comment by r00t34** [comment]
I don't have any problem with Google Dialer my friend. I couldn't understand why you closed the case without solve. I want to debloat my phone but you are not solving the problems. This is sad. Really sad.

**Comment by esprit-libre** [comment]
Hello,
I also have the same behaviour. Is there a way to link system notification to call history in Simple-Dialer ?
Each time I miss a call, system notification increment the number of missed calls even if I consult history or if I tap on notification.
Any idea ?
Many thanks for your help

**Comment by billie80** [comment]
Sorry but I also think this is a valid request.
If there is are missed calls and I open the Native Dialer, there is an indicator with the number of the missed calls in the call history. When I click call history this is cleared.
With Simple-Dialer this is not possible. I can click on the missed call notification and nothing happens. I also can not clear this by opening Simple-Dialer manually to clear this missed call. So it keeps popping up on every reboot.
So I have to open the Native Dialer to clear the missed call there.

Is there no way to route to Simple-Dialer from the notification or at least make it possible to clear it from within the app?
