### ISSUE TITLE
Dialer history not updated, only after swiping away the screenshot-version it appears correctly

### ISSUE THREAD

**Issue by pieterjoanUvA** [SimpleMobileTools/Simple-Dialer#135]
Hopefully not a double issue, but it was peculiar enough for me to just mention.
I like your apps, the f-droid versions, on my samsung Android 10 skinned version.
fyi, the dialer, sms and contact apps are my primary versions, also I tried the Google versions,
but those are or only beta-invite-forced, or a bit odd working.

Love the simplicity of these apps, also the unexpected working couplings of my physical home-button_to_answer-call
customisation of the Xcover 4s, with physical home,back,prgrm buttons. 

Thanks for all your efforts, it took me a full year to get seduced by true simplicity over apparent subtleness of gui-non-importantness and proving those supposed extra's are not needed in my use cases.

With regards, like a stubborn child.

Pieter Joan :-]

**Comment by tibbi** [comment]
Hey, not sure what you mean here. Dialer history isnt updated correctly, only if you restart the app, or what? Thanks

**Comment by pieterjoanUvA** [comment]
Sorry for the unclear description.
I called a local landline, then I opened the history-calls tab and the number was not listed.
Yes, your assumption is correct, the screenshot-swipe that closes the app was needed.
then reopen the app, and the call is listed in the history tab.
If you would like more info, adb stuff [please supply commands], screenshots ed. please let me know.
hopefully this creates a more understandable description. 

hmm, i just tested it again with a different case, the back-button, then re-click the phone icon also solves the problem.
But it does not always occur consistently. 
my third test with the app still open, and the back-button__re-click-icon, first correctly listed update [status off my previous actions].
Then I retried to call the same number with a different sim, and the call was listed immediately.

[also with simple sms, my sim is sometimes labeled -?-, and not -1-,-2-, but that is a different app, and rare dual-sim-usage i think. if you'd like i could provide screenshots of that issue, in private or public with message blanking ]
with kind regards, Pieter Joan

**Comment by pieterjoanUvA** [comment]
Thanks 👍
