### ISSUE TITLE
Simple Dialer forgets that it is the default phone app

### ISSUE THREAD

**Issue by genodeftest** [SimpleMobileTools/Simple-Dialer#138]
Steps to reproduce:
1. Open _Simple Dialer_
2. switch to the history
3. click on any entry
4. watch the screen

What happens:
A popup dialog is openend (by system or simple dialer app? I don't know) which lets me choose whether I want to use the stock phone app or simple dialer:
![simple-dialer-choose-phone-app](https://user-images.githubusercontent.com/934401/103463899-030ec280-4d30-11eb-818c-249ffd01df88.png)

What should happen:
Because I chose "Dialer" with "ALWAYS" before, this dialog should not pop up any more. It should always use simple dialer.

Additional info:
It seems like this issue does not happen when calling from other apps, e.g. simple contacts. When using simple contacts to call a contact, it always directly opens the dialer and does not ask whether I want to use _Dialer_ or _Phone_.

Hardware:
Nokia 5 (HMD Global TA-1053)

Software:
Android 9 patchlevel 2020-10-01
Simple Dialer v5.5.4 installed from f-droid store

**Comment by tibbi** [comment]
I cannot reproduce it, seems to be some system issue. Anyway, try it with 5.6.0 once it becomes available.

**Comment by genodeftest** [comment]
I can still reproduce it with 5.6.0. This is no major issue though, so if you don't think it can be fixed, feel free to close this issue.

**Comment by omar-mohy** [comment]
This issue still happens on 5.17.3
