### ISSUE TITLE
Android 11 - Can't add contacts to Speed Dial

### ISSUE THREAD

**Issue by andrei-belkin** [SimpleMobileTools/Simple-Dialer#139]
Hello,

I'm unable to assign my contacts to Speed Dial buttons. When I open the "Manage speed dial" option in the settings, I see this : 

![Screenshot_20210102-164302](https://user-images.githubusercontent.com/59848424/103467107-b5726580-4cef-11eb-8e30-cb28bdf437e2.png)

When I tap (short tap, long tap, doesn't matter) one of these slots, absolutely nothing happens. No popup, no nothing.

App version: 5.5.4
Android version: 11
Hardware: Google Pixel 4a

Is there something I'm missing?

Thank you for your time.

Cheers,
Andrei Belkin.

**Comment by tibbi** [comment]
a single click should make a popup with contacts appear. Try upgrading to 5.6.0, however, nothing related has changed I guess. It works well on my Android 11.
