### ISSUE TITLE
Feature Request: Optional drop-down incoming call notification

### ISSUE THREAD

**Issue by Midi-In** [SimpleMobileTools/Simple-Dialer#140]
Currently Simple Dialer occupies the entire screen whenever an incoming call is awaiting user action. This can very unexpectedly interfere with any activities the user might be in the middle of (like typing on Discord or placing notes in a music sequencer for example), often leading to accidental pick ups of the call (especially without the swipe to pick up implemented) which can be very frustrating.

One possible solution is to add an optional mode of operation where the application only shows a small drop-down menu at the top, much like the default Google dialing application.

Example: https://docs.counterpath.com/docs/AndUG/Resources/Images/UG/AndroidRetail/calls/mc_headsupNotification_And.png

**Comment by dtbj** [comment]
Yes I also want this please implement this.

**Comment by tibbi** [comment]
will be added in 5.13.0
