### ISSUE TITLE
FR: Allow changing sorting method like in Simple Contacts

### ISSUE THREAD

**Issue by Gitoffthelawn** [SimpleMobileTools/Simple-Dialer#145]
Once https://github.com/SimpleMobileTools/Simple-Contacts/issues/647 is fixed, can you add the ability for the user to change the sorting method just like in Simple Contacts?

**Comment by TheModernWizard** [comment]
I would love to see this feature! It would be ideal to have the sorting functionality be the same in Contacts and Dialer.

**Comment by tibbi** [comment]
it will be possible to sort by full name and date created soon. Not by all those Contacts fields yet as Dialer works differently.

**Comment by Aga-C** [comment]
It's already implemented.

**Comment by Gitoffthelawn** [comment]
Thank you!
