### ISSUE TITLE
Block unknown (as in not part of the contacts) phone numbers

### ISSUE THREAD

**Issue by tmortagne** [SimpleMobileTools/Simple-Dialer#146]
Would be great to support a kind of dynamic white list based on the registered contacts instead of the current configured black list.

This is for the phone of my kid and I see no reason for anyone who is not in the registered contacts to be allowed to call her.

**Comment by tibbi** [comment]
this has already been added

**Comment by tmortagne** [comment]
> this has already been added

Do you mean it was already there when I created this issue and I just could not find how to do it, or was it added recently ?

**Comment by tibbi** [comment]
it has been added just recently in 5.13.0

**Comment by tmortagne** [comment]
OK thanks @tibbi I had not tried again since I created this issue.
