### ISSUE TITLE
Call Log - Exact Timestamp

### ISSUE THREAD

**Issue by ace2k** [SimpleMobileTools/Simple-Dialer#147]
Hi, is there a way to display the exact timestamp of past calls in the call history?
For today's calls you see `hh:mm`, for everything else you only see the day/month/year, but can't see what hour/minute the call happened.

Here's a screenshot of my recently missed calls. I have no way of telling ***when exactly*** the yesterday's calls happened, only that it was in fact yesterday. A precise timestamp would be nice, I have tried out different date display formats in the app settings.

Version 5.6.0 from F-Droid.

Any help appreciated! Thank you!

![timestap](https://user-images.githubusercontent.com/46848252/104479132-5d771100-55c3-11eb-96ad-59e80a47b7f7.png)

**Comment by sebasarena** [comment]
I'm using the version 5.6.1 from F-Droid in Android 10.

I also would like to know the timestamp of all the calls. Until now, I needed to write down in paper the timestamp myself, to keep the record of my call logs.

But if the app can have a more complete call log, it would more helpful for everyone. Thanks for all the effort!

**Comment by lucamp** [comment]
This would be very useful since reporting a spam phone calls to the authority requires date and time
