### ISSUE TITLE
Call waiting

### ISSUE THREAD

**Issue by test2a** [SimpleMobileTools/Simple-Dialer#148]
Unable to see call waiting setting. I had removed the stock phone app and now I am unable to do setting for call waiting/forwarding in simple dialer

**Comment by sah-anshu** [comment]
+1  Very Imp. Feature

**Comment by pi-x-el** [comment]
+1 Imp Feature

**Comment by TheCodingArcher** [comment]
This is one very important feature which will be needed ASAP. Not sure about your priority but as a user, it is prior to me.
