### ISSUE TITLE
Dialer does not respect default number on contacts with multiple numbers

### ISSUE THREAD

**Issue by matejdro** [SimpleMobileTools/Simple-Dialer#15]
At the moment, selecting a contact that has more than one mobile number will just call one of his numbers.

Instead app should call the number that was set as default in the contacts.

**Comment by ltGuillaume** [comment]
I get to see two entries for a single contact with two numbers, but there is no way whatsoever to see which number is which. I think every entry should at least have their respective number below it OR "Mobile"/"Home"/"Business" etc. below it.

**Comment by tibbi** [comment]
it asks it already
