### ISSUE TITLE
Does it possible to enable (self) contacts storage please?!

### ISSUE THREAD

**Issue by hamedsbt** [SimpleMobileTools/Simple-Dialer#153]
I'm aware about my privacy, so I'm using awesome **Simple-Contacts** app with **self-contacts storage**. now I prefer using an integrated **Simple-Dialer** with **Simple-Contacts** together with  **self-contacts storage**. can you do it please?

**Comment by ericabrks** [comment]
8505320885 Josh King

**Comment by tibbi** [comment]
just store the contacts under "Phone storage (not visible by other apps)"

**Comment by hamedsbt** [comment]
Thank you for reply.
In "Simple-Dialer" app I have only one option: **Saving to Device** (above _First Name_ field). Does **Saving to Device** mean Phone storage (not visible by other apps) ?!

**Comment by tibbi** [comment]
where in Simple Dialer? You cannot manage contacts there, use Simple Contacts Pro for that.
