### ISSUE TITLE
Search on other than names and numbers

### ISSUE THREAD

**Issue by esprit-libre** [SimpleMobileTools/Simple-Dialer#159]
[Note: I transfer my request misaddressed in [Simple-Contacts#657](https://github.com/SimpleMobileTools/Simple-Contacts/issues/657)]

I used a lot search by company name, but it does not work with Simple-Dialer. This would be great if search could include also other fields like company, postal address, etc, as does Simple-Contacts.

Many thanks for your apps!!

**Comment by tibbi** [comment]
it wont be added into Simple Dialer, it isnt aware of the company and all those fields
