### ISSUE TITLE
Wear OS companion

### ISSUE THREAD

**Issue by matejdro** [SimpleMobileTools/Simple-Dialer#16]
It would be useful to have Wear OS companion that would allow initiating calls from the watch (useful when user has headphones with mic already connected for example).

I am prepared to submit pull request for this at some point (can't offer any ETAs, I'm having too many open projects at the moment :smile:) if authors agree with the feature. However, one issue with this is feature is that it relies on Google Play Services which would prevent release of the app on any other store than Play Store (including F-droid).

**Comment by tibbi** [comment]
I dont want to add any Google Play Services, thats for sure. Im not really sure how does Wear OS work. If it really has to include Google Play Services, it wont be added.
