### ISSUE TITLE
Contact cannot be found without diacritics

### ISSUE THREAD

**Issue by ph-legacy** [SimpleMobileTools/Simple-Dialer#163]
Names like

- Petr Šilhavý
- Anežka Nováková

Cannot be searched by query `silh` or `anez` (without diacritics).

It would be really handy to have it.

![Screenshot_20210301-120051_Dialer_1.png](https://user-images.githubusercontent.com/383295/109488780-4d899280-7a86-11eb-8f67-9f611c2cbc7f.png)

![contacts2.png](https://user-images.githubusercontent.com/383295/109488864-672ada00-7a86-11eb-9264-0262a036fddd.png)

**Comment by tibbi** [comment]
this has been fixed already
