### ISSUE TITLE
Ongoing call layout looks wrong on small screens

### ISSUE THREAD

**Issue by voussoir** [SimpleMobileTools/Simple-Dialer#169]
Hi @tibbi,

This screenshot comes from a Unihertz Jelly 2, with a screen resolution of 480x854 and font size set to Large. I am not sure if the upper space is reserved for something, but could the dialpad be given priority over the upper space for layout?

![2021-03-19_16-56-48](https://user-images.githubusercontent.com/7299570/111857041-11f72100-88ec-11eb-86fe-4d6a403a402d.png)

Thank you!

**Comment by tibbi** [comment]
should be better in 5.7.+
