### ISSUE TITLE
Refuses to dial a number

### ISSUE THREAD

**Issue by azat11** [SimpleMobileTools/Simple-Dialer#171]
Tried my bank's support number, and it just does not dial it.
This number is working btw, I checked.
Had to use another number.

Bug, I guess.

CM 13.1, OnePlus One.

**Comment by tibbi** [comment]
What exactly happens? What app version are you using?

**Comment by azat11** [comment]
I type in the number, press dial, and it flashes dialing screen for a moment, and just does nothing.
It was 5.6.1, updated to 5 6.2, same deal.

**Comment by tibbi** [comment]
do other downloaded Dialer apps work?

**Comment by azat11** [comment]
I did call this number before with other dialers, yes. But didn't test it recently.

**Comment by azat11** [comment]
I think I found the cause. I just had the same trouble dialing a number. Both numbers contain "555" in them.

**Comment by tibbi** [comment]
guess your app wasnt set as the default for handling Phone calls, check if the behaviour changes with 5.8.0. You should be redirected to the device settings.
