### ISSUE TITLE
Multi sim support

### ISSUE THREAD

**Issue by AlphaDE** [SimpleMobileTools/Simple-Dialer#174]
Coming from a Oneplus 7 Pro (and the Oneplus dialer), I would like to see a way to select the sim card to use on the dialer when entering a number. 
Oneplus uses two dial buttons, annotated with the sim card number (the default one bigger and centered, the other one left and smaller). 
That way, the user has the option to make an informed decision which sim to use. 

As calls show the sim card used in the history, I assume that the same sim is used when calling back.

Within the "Simple" ecosystem, it would be great if the contacts app would allow to assign a default sim for a contact or to define some simple rules which sim card to use (for example based on the country prefix). 

Although the description states "multi-sim support", I did not find any of these features in the configuration.

I would be a great addition for the Simple tools and make them even more worthy.

**Comment by tibbi** [comment]
you can do it already no? Select what SIM you want to use, unless you have set some default already

**Comment by AlphaDE** [comment]
Tibor, thanks for your reply.
But then I have to select that for each and every call. The option by having two dial buttons is much more convinient... and some sort of preselection/suggestion for example based on the prefix

**Comment by tibbi** [comment]
dont you have a "Set as default" check at the bottom of the SIM picker?

**Comment by AlphaDE** [comment]
Which sim picker do you mean?

My problem:

I have two sim cards (that's why a dual sim mobile is a must). One German, one US.

To call or text US numbers using the German sim is expensive, with the US sim, texts are free and calls are at $0.20/min.
To call or text German numbers using the US sim does not make sense either, texts remain free and calls are at $0.20/min, but with my German sim, I have an all-net flat and people will not reply to an US phone number.

So best would be to allocate sims to contacts and at least see and be able to easily switch to the right sim when calling (but not make this decision on each and every call).

The Oneplus dialer I used with my previous Oneplus 7 Pro had two dial buttons. In the center a bigger one showing the current active sim and left of that a smaller one for the other one. One could easily switch between both.

I would love to see some sort of support for multi sim in such a manner.

Even more (when combining Simple contacts and Simple dialer) assigning sim 1 or sim 2 to a certain phone number or at least a certain contact... in Simple dialer, some sort of user settings like "use sim 1 on all numbers starting with +1 and so on) would be great, too.

I am aware that there aren't that many people with multiple sims from different countries but that's the power of a multi sim phone.

**Comment by tibbi** [comment]
try selecting the wanted contact by long pressing and use the top Menu -> Call with SIM 1 or so.

**Comment by AlphaDE** [comment]
Great, did not see that before... 

So an option for the dialpad would be great to choose one of the sim to make the call.

**Comment by tibbi** [comment]
isnt it asked too at calling new unsaved numbers?

**Comment by AlphaDE** [comment]
No, just called a local 0800 number and it immediately dialed.

**Comment by csando** [comment]
Hello just a note, I also have this problem and would appreciate a Sim picker when dialing. If I dial an unsaved number it just uses sim #2

**Comment by maximilianovermeyer** [comment]
Did you activate the option "Ask every time" in the Android settings for "Calls preference"?
Settings -> Network and Internet -> Select any SIM -> Calls preference

**Comment by tb06** [comment]
> Did you activate the option "Ask every time" in the Android settings for "Calls preference"? Settings -> Network and Internet -> Select any SIM -> Calls preference

On my side I discovered (late) this good solution :-)

**Comment by tb06** [comment]
> No, and I don't want to do that. I just want to assign some contacts to a specific sim and neither need nor want to decide this on every call.
> 
> So, looking at the age of this issue, I understand that multi sim support as implemented by other dialer apps is not intended. A pity, makes the app rather useless, I already switched back to the stock dialer which offers this feature.

Just before calling I get this, with a checkbox to choose a permanent option:

![image](https://user-images.githubusercontent.com/51849819/149402281-8a54ec92-6851-4248-b928-22e7b2228860.png)

**Comment by AlphaDE** [comment]
See my initial description, the default sim suits me very well... When in the US, all calls and texts go via the US sim, in Germany most calls use the German sim. So the way the stock dialer does by offering a primary and a secondary dial button is the easiest.
