### ISSUE TITLE
Unable to delete contacts

### ISSUE THREAD

**Issue by eleius** [SimpleMobileTools/Simple-Dialer#175]
I just installed the latest version available on f-droid. Since I have several duplicates, I tried to delete some contacts, but when I launch the app again, the deleted numbers were still there. I also tried to select them all and delete them, but they reappear immediately.

**Comment by tibbi** [comment]
what numbers you mean? From the Recents tab? Try disabling missed call grouping in the app settings, maybe thats the issue
