### ISSUE TITLE
call log/ history always showing sim 2 icon 

### ISSUE THREAD

**Issue by jithin-kg** [SimpleMobileTools/Simple-Dialer#176]
in call log / history tab call log is always displayed as sim 2 .
Value of **simID** in RecentsHelper.kt is **always 2** in dual sim device even if called with sim 1

**Comment by tibbi** [comment]
do other Dialer apps show it well?

**Comment by jithin-kg** [comment]
no, other apps shows accurately.

**Comment by tibbi** [comment]
and how are your SIM cards identified then?

**Comment by Coolporteur** [comment]
Hi, i have same problem with this app, only sim 2 display in call log even if called with sim 1 ...
I have Xiaomi note 9t 5G MIUI 12.0.6

**Comment by tibbi** [comment]
retest if it will still be broken in 5.7.0. Or if you want to check out a test version even earlier, just let me know. Ideally at hello@simplemobiletools.com, it is easier to send files there.

**Comment by tibbi** [comment]
duplicate of #41
