### ISSUE TITLE
Grid view for favorites

### ISSUE THREAD

**Issue by aktolu** [SimpleMobileTools/Simple-Dialer#179]
For older aged users (who have problem is them eyes), maybe will better option is favorites listing with two columns grid view with contact photos.

**Comment by dtbj** [comment]
Yes I also want this please implement this.

**Comment by da-anda** [comment]
I am also looking for a good dialer for my parents and a grid view for the favorites would be awesome

**Comment by v0iden** [comment]
I would like this, too. would be very convenient.

**Comment by SIRSteiner** [comment]
This feature is present in v5.18.1. I think you can close this issue.

**Comment by tibbi** [comment]
some UI improvements will still be done, but ye, it is there already

**Comment by da-anda** [comment]
thank you so much. The app is so much easier to use for my dad now. Thanks.
