### ISSUE TITLE
Improve visualization of grouped history

### ISSUE THREAD

**Issue by igor-cali** [SimpleMobileTools/Simple-Dialer#181]
When the '`Group call with same number`' is active, multiple entries for the same contact are shown depending on the call timestamp.

E.g. (most recent first):

```
- Contact1
- Contact1
- Contact2
- Contact1
- [...]
```

Shown current:

```
- Contact1 (2)
- Contact2
- Contact1
- [...]
```

Proposed:

```
- Contact1 (3)
- Contact2
- [...]
```

**Comment by tibbi** [comment]
I dont want to add that, looks too confusing
