### ISSUE TITLE
Call log history is counting double

### ISSUE THREAD

**Issue by golot86** [SimpleMobileTools/Simple-Dialer#184]
received and accepted or missed calls are counted double in the call history, that is both in the Simple Dialer history, as well as the Android Phone history.

My setup is the following:
- Lineageos 18.1
- Simple Dialer 5.4.6 via F-Droid, set es default app
- Simple Contacts 6.14.3, with setting "show private contacts to Simple Dialer"

**Comment by tibbi** [comment]
what do you mean by double? If you have 1 received call it shows up twice?

**Comment by golot86** [comment]
> what do you mean by double? If you have 1 received call it shows up twice?

Yes indeed. Likewise if a call is missed.

**Comment by tibbi** [comment]
what happens if you delete one item? Do both of them disappear?

**Comment by tibbi** [comment]
if you use the system Phone app for handling calls, does the default Android Phone app show it well? Or it is like always broken?

**Comment by Canecat** [comment]
The same behavior on crDroid (Android 11)

**Comment by tibbi** [comment]
doesnt sound like an apps issue then

**Comment by ernzem** [comment]
Have the same issue: Call log history is double.

Pixel 4a (stock Android 11):
 - Simple Dialer 5.7.0
 - Simple Contacts 6.15.0
  -Simple Dialer is set as default Phone app. However stock "Call" is not disabled (not allowed). Stock "Call" app doesn't have any records about contacts or call history.
  
I opted to not group the same calls. Deleting one duplicated record removes the one selected record (not both). Let me know if can help you with solving this issue.

**Comment by Canecat** [comment]
> The same behavior on crDroid (Android 11)
The same behavior on AOSP 11.
Now the stock dialer is not disabled.
In stock dialer there is only one record for each call in the simple dialer there is two of them.

**Comment by Canecat** [comment]
It looks like call history entries are doubled only when call was successful, if you call some number and then drop it before connection was established then only one entry is placed in the log.

Jun 12, 2021 21:11:53 Tibor Kaputa ***@***.***>:

**Comment by SimonMellerin** [comment]
Hi,

Same trouble here with:

* Pixel 4a/CalyxOs
* "Stock Phone app" is disabled

When someone try to call me, class appears twice in my history. If I delete one, the other one stay in place.

**Comment by xunil89** [comment]
I also experience the same bug on a 11 arrow codename miatoll. I should add that I can't mark missed calls as "read" and on every restart they reappear. Simple has all the appropriate permissions and is set as the default app but android call manager keeps notifying it on every restart of missed calls. (Unfortunately I don't use the vanilla version but anyway all google call management apps are hibernated )

**Comment by foliage-burner** [comment]
I am experiencing this issue as well on a Moto G Fast with Android 11. From what I can tell, this issue only occurs in Android 11, so the call system may have slightly changed in the update.

**Comment by damianorenfer** [comment]
Same here on Nokia X20 with Android 11 and stock phone app (Google) disabled.
