### ISSUE TITLE
Block outgoing / international numbers

### ISSUE THREAD

**Issue by wandhydrant** [SimpleMobileTools/Simple-Dialer#187]
Hello!

It would be nice to protect oneself from accidental outgoing calls. For example, when you have many international contacts but don't want to phone them over your mobile network.

This seemed possible in the default app ("call barring") but to me that one just throws a "Network or SIM card error".

If one were able to put a list of regexes, one could block not just international calls, but also other expensive numbers. If you really want to make a call, you could switch off the block.

Thank you for all your work!

**Comment by tibbi** [comment]
I dont really plan adding that
