### ISSUE TITLE
Incoming call not showing up (but ringing)

### ISSUE THREAD

**Issue by golot86** [SimpleMobileTools/Simple-Dialer#188]
I received a call, the phone was ringing, but nothing was displayed to take up the call.

My setup is the following:

- Lineageos 18.1
- Simple Dialer 5.4.6 via F-Droid, set es default app
- Simple Contacts 6.14.3, with setting "show private contacts to Simple Dialer"

**Comment by tibbi** [comment]
was he screen turned on when it started ringing?

**Comment by golot86** [comment]
Yes it was. 

To describe the scenario in detail:

I was in a call, and (probably) by accident airplane mode was activated. Shortly after I deactivated the airplane mode the other party called back but as described as above, the phone would only ring, nothing was displayed to accept the call.

@tibbi: I really appreciate your effort with this project. Unfortunately Simple Dialer seems to be to unstable for my phone setup. So for now I need to switch back to the Android apps. But please, keep up the great work!

**Comment by glzlaohuai** [comment]
Same issue here, OS is MIUI 12.5

**Comment by tibbi** [comment]
try enabling app to be shown above other apps in your device settings, will be added in 5.7.0

**Comment by tibbi** [comment]
Another user reported it with Poco phone

**Comment by Sidez51** [comment]
Hi. Recently discovered your apps on f-droid. Thank you.
Poco x3 pro, MIUI Global 12.5.2.0 stable (RJUEUXM).
Using sms messenger, simple contacts and simple dialer.
My phone rings but no incoming call notification. Can't answer call. Need to wait for ringing to end, then check call log and call the missed call.
Other than that the dialer works perfectly

**Comment by tibbi** [comment]
@Sidez51 if you check your device settings, isnt there a list of apps that are allowed to show above other apps? Or a similar list which shows some other Phone eapps, but doesnt even list Simple Dialer?

**Comment by Sidez51** [comment]
> @Sidez51 if you check your device settings, isnt there a list of apps that are allowed to show above other apps? Or a similar list which shows some other Phone eapps, but doesnt even list Simple Dialer?

**Comment by Sidez51** [comment]
Thank you for your swift reply. 
After reading these comments I enabled that setting. When somebody calls I'll post the result

**Comment by Sidez51** [comment]
Joy of joys. That worked. 
Thank you for that and sorry to bother you with such a daft question

**Comment by tibbi** [comment]
how do other downloaded Phone apps work? Do they show a warning at app launch to enable that setting?

**Comment by Sidez51** [comment]
The other apps work perfectly, but no warning to enable that setting

**Comment by tibbi** [comment]
and if you check those other apps, is the option for showing over other apps enabled by default?

**Comment by Sidez51** [comment]
Contacts and SMS Messenger aren't listed in the show over other apps section. Only Dialer is listed.
However, I am getting notifications for incoming text messages

**Comment by tibbi** [comment]
I talk only about the dialer app, not others. By "other apps" I meant some competition Dialer/Phone apps, not ours.

**Comment by Sidez51** [comment]
Ah, sorry about that. I don't know. When I received this phone I immediately debloated followed by installing your apps and then used adb to disabled the stock apps.

**Comment by tibbi** [comment]
recheck with 5.9.0, let me know if it works already

**Comment by glzlaohuai** [comment]
Just tried 5.9.0 but nothing changed.

Mi10 with MIUI OS 12.5.7

**Comment by ChrisGCode** [comment]
Is it possible that the gradle version has an impact?
When I build without gradle update I have this issue as well.
Or is it only an effect of a dirty cache, or ... and not related to the gradle?

I use conversations (https://github.com/iNPUTmice/Conversations) and I do not have issues when I receive calls in conversations.
Therefore I looked into conversations and saw the additional flags, I added in my build.

Just an idea:
@glzlaohuai, perhaps you can try conversations (available @f-droid). If it works for you, tibbi could check the differences in the src.

**Comment by tibbi** [comment]
I dont think gradle can impact it in any way, but anything can happen on Android.

**Comment by KryptKode** [comment]
@ChrisGCode Please what android version is your device running on?

**Comment by ChrisGCode** [comment]
> Please what android version is your device running on?

LineageOS 16 (Android 9), private build, running on santoni

**Comment by tibbi** [comment]
recheck with 5.10.0 please, if it still happens

**Comment by ChrisGCode** [comment]
1st call after installation was fine.
Then it seems to be a bit sporadic.
A race condition that could explain why my change (gradle + on my phone dead code) worked for me at all?
(Sorry, I was a little too enthusiastic when saw it worked and submitted the pull request.)

**Comment by tibbi** [comment]
Well if you have a rooted device, it can have tons of device specific issues. Im honestly more interested in fixing the behaviour for casual users.

**Comment by tibbi** [comment]
version 5.12.0 will have a snackbar at the bottom redirecting you to "Draw over other apps" setting, check if it will work

**Comment by cenktaskin** [comment]
Using on Android 10. Have the issue. Drawing over other apps is allowed, battery optimization is disabled. When screen is locked, it rings with empty screen. I use a launcher if that is important. On version 5.11.3. This morning I went to Duraspeed and disabled Duraspeed for Dialer in case it is the thing causing the issue.

**Comment by tibbi** [comment]
check your device security settings if you wont find something there

**Comment by cenktaskin** [comment]
Hey,
*To be clear,* I don't now if the issue was Duraspeed. I will update if it persists.
Just had a trial call incoming from a friend, and it works as expected, so good.
But I will let it have couple days to test and see in more configurations.

**Comment by Aurjo1** [comment]
Hi tibi,
I have the same problem with incoming call's. I have version 5.11.4 and Android 11. I'm very happy with your dialer and your contact app. 
The show above other apps is enabled. 
And I only have the problem if simple dialer is closed while screen lock is activ.
It doesn´t matter wether the screen is black or showing.
If simple dialer is runing also in the background. The call will showing up.
Even when screen lock is activ.
I have no security apps on my phone.
Thanks for helping.

**Comment by Aurjo1** [comment]
I just tried to turn duraspeed on and now it seems to work but I will have an eye on it and I'll update.

**Comment by Aurjo1** [comment]
It´s working. With Duraspeed on it´s working perfekt. 5 Stars.

**Comment by tryfon** [comment]
OK, in my case I fixed it by going to Settings->Permissions->Other Permissions->Dialer and enabling "Show on Lock screen", "Display pop-up windows while running in the background" and "Display pop-up window" permissions. It was probably the first one that did the trick. I guess the App should check and request these permissions every time it is used (at least the first one). 

Simple Dialer v5.11.5 on a Xiaomi Note 9 Pro with MIUI 12.5.7.0 (Android 11)

**Comment by IronFluffy** [comment]
Simple Dialer 5.11.5 on a Ulefone Armor X9 pro with Android 11

I have the same issue. If the phone is locked, the screen will turn on and I can hear the ringing, but nothing appears on the screen. Even after unlocking the phone, I need to launch the dialer app to be able to respond to the incoming call. The permission to show on top of other apps is enabled.
