### ISSUE TITLE
keyboard problem

### ISSUE THREAD

**Issue by Tintinet** [SimpleMobileTools/Simple-Dialer#189]
When i use this app to call someone or receiving one, the keyboard disappered so i can't stop the conversation and i can't use numbers to select some issues.

**Comment by tibbi** [comment]
What do you mean? Why cannot you end the call for some missing keyboard?

**Comment by Tintinet** [comment]
When i use this app, 5 seconds after the call nothing was displayed to accept/finish/use the loudspeaker/using numbers... during the call. The app closed the interface. It could be due to my phone, a LOGICOM Le prime.

**Comment by tibbi** [comment]
do you see a notification at the top?

**Comment by Tintinet** [comment]
Yes but when i click on it, it disappered.

**Comment by tibbi** [comment]
there will be multiple related changes in 5.7.0, reopen if it is still misbehaving
