### ISSUE TITLE
Missed call notification does not open simple dialer

### ISSUE THREAD

**Issue by BigNdets** [SimpleMobileTools/Simple-Dialer#190]
The missed call notification from call management leads to choosing a default dialer app which doesn't include simple dialer even with simple dialer set as the default dialer app.
My set up is:
Android 10

**Comment by tibbi** [comment]
what app version are you using?

**Comment by BigNdets** [comment]
> what app version are you using?

V 5.6.4

**Comment by tibbi** [comment]
try 5.7.0, should be working there
