### ISSUE TITLE
Android 5.0 (min sdk 21) support, please!

### ISSUE THREAD

**Issue by DI555** [SimpleMobileTools/Simple-Dialer#191]
please, add support for Android 5.0 (min sdk 21), please!
many thanks in advance!

**Comment by tibbi** [comment]
it isnt worth it, current requirement has been added for technical reasons

**Comment by DI555** [comment]
it is worth it!
many of us and i have multiple android 5.0 devices!
and we're using SimpleContacts, which is 'min sdk 21'...

**Comment by DI555** [comment]
yes, custom calling window won't work, but other will work greatly!
