### ISSUE TITLE
Calling from Call Log hangs with Dual Sim

### ISSUE THREAD

**Issue by danml3** [SimpleMobileTools/Simple-Dialer#193]
When tapping a number in the call log or contacts inverface to call the person, the Dialer changes screen to display only Contact name and their number below it, but does not dial and just hangs. No buttons show. This is Android 9 with 2 sim cards inserted. No default sim is selected for any contact in Dialer and Android setting: Preffered sim for Calls is set to ask every time. 

If i dial a number manually, a prompt comes up to chose which sim to use and upon selection dialling is successful. Tapping outside of the sim selection prompt reproduces the hanging behaviour. If I select a default sim in the Android Settings, Preferred SIM for calls then the Dialer works correctly without hanging

**Comment by tibbi** [comment]
what app version and OS version are you using?

**Comment by danml3** [comment]
App version 5.7.0, Android 9, kernel 4.4.180.

Thank you

**Comment by tibbi** [comment]
retry with 5.12.0
