### ISSUE TITLE
Issue: Call Blocking not working

### ISSUE THREAD

**Issue by mtris** [SimpleMobileTools/Simple-Dialer#198]
![SCREENSHOT20210701](https://user-images.githubusercontent.com/24400330/124175552-4490e800-da9d-11eb-8ab3-2eaed9d5ade9.png)
Dear SimpleMobileToolsPro Team: Your apps are amaze, and was hoping you'd advise me on my Call Block not working. Each time I try it, I receive the error message displayed in my attachment. 
Is it possible I disabled a necessary app needed?
In any case, thank you for your dedication and consideration. Sincerely,

Andoid 9 on a LG V40 with Dialer app v5.7.0 via F-Droid

**Comment by tibbi** [comment]
Hello, how are you doing it? You use the Block number menu option from the Recents tab?

**Comment by mtris** [comment]
> Hello, how are you doing it? You use the Block number menu option from the Recents tab?

Hi there: Yes. Recents tab, I long-press the contact to highlight it, then into the menu to select Block Number

**Comment by tibbi** [comment]
is it some casual number, or something extra? Does call blocking with from the app settings and entering a number manually?
