### ISSUE TITLE
Start name with surname function bug

### ISSUE THREAD

**Issue by Fehertukor** [SimpleMobileTools/Simple-Dialer#199]
I have version 5.7.0
And the start name with surname function does not work.

**Comment by tibbi** [comment]
If you check the contact details in Simple Contacts or other similar app, do you have the contact name properly filled out at First name and Last name fields at all? Havent you just inserted the whole name into 1 field?

**Comment by Fehertukor** [comment]
Interestingly, when i wrote the ticket I have tried turn this option ON/OFF and did not help.
But I have checked again and it seem to work.

Thank you for your amazing work on Simple project:)!!
