### ISSUE TITLE
[Feature Request] Add a possibility to copy a phone number from the block list

### ISSUE THREAD

**Issue by Aga-C** [SimpleMobileTools/Simple-Dialer#203]
Hi,
It would be useful to have a possibility to copy a phone number from the block list. Sometimes I'd like to check information about blocked number on the Internet and that functionality would make it easier.
Thanks!

**Comment by tibbi** [comment]
actually you can already select a Recents entry by long pressing it and using "Copy number to clipboard" at the top menu.

**Comment by Aga-C** [comment]
@tibbi But it won't work in situations when I've added number to blocked some time ago and would like to check why I did it. Copying would be useful in such case.

**Comment by tibbi** [comment]
Right, I havent noticed that you mean the block list

**Comment by tibbi** [comment]
actually I just implemented it, will be added in 5.8.0
