### ISSUE TITLE
Option to ungroup calls in log

### ISSUE THREAD

**Issue by groundtm** [SimpleMobileTools/Simple-Dialer#21]
Please, add an option to ungroup calls from the same person/phone number in the log. Now, if somebody calls me 3 times in a row, there is "(3)" mark behind the caller name. I would prefer to have each call as single entry in the log, so I know when each call happened and what was its duration.
Many Thanks.

**Comment by ltGuillaume** [comment]
I don't even see the a timestamp for a call, only the date and duration?

**Comment by judge2b** [comment]
The call history is very frustrating without this feature because I can't see the duration and time of each individual call. This would be a very appreciated feature.
