### ISSUE TITLE
Feature Request: Sticky/Non-dismissable Notification during Call

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/Simple-Dialer#23]
I'd love to see a sticky/non-dismissable notification in the Notification Shade during a call in case the Dialer app gets closed/dismissed.

User story:
My wife accidentally dismissed the Call screen during a call, and was unable to navigate back to the Call screen to toggle Speakerphone/dialpad/call controls/etc.

**Comment by Twiub** [comment]
Yes sometimes once you hit back the screen disappear and you cannot receive the call

**Comment by test2a** [comment]
yes. i switched to this dialer and this is one of my most painful papercuts. i have to ask the other side to cut the call on their side and then i am able to start a new call.

**Comment by tibbi** [comment]
there is already a notification, leaving the app with back button ends the call

**Comment by Saijin-Naib** [comment]
> there is already a notification, leaving the app with back button ends the call

Yes, and this UX is fundamentally poor for people. I've had to uninstall Simple Mobile Dialer from all of my family's devices because I get constant complaints about how the calls keep "crashing", and I found out it was due to this UX being so unexpected for them.

**Comment by tibbi** [comment]
ye, but that is a different issue at #104 , it isnt really related to the notification
