### ISSUE TITLE
No numbers in history If date is before Install date

### ISSUE THREAD

**Issue by cha0s184** [SimpleMobileTools/Simple-Dialer#24]
Look at the last two calls in the Screenshot
![Screenshot_2020-05-20_14-34-54_1](https://user-images.githubusercontent.com/65662178/82446840-a9f76480-9aa7-11ea-912f-a9f9b190d3ed.png)

**Comment by tibbi** [comment]
are they calls from casual phone numbers? Do other apps display them well?

**Comment by cha0s184** [comment]
What so you mean with casual? They are not saved under contacts...the Google dailer displays them correct.

**Comment by tibbi** [comment]
what does Google Dialer show them as? Is it the contacts name? Is it maybe some organization and not a person?

**Comment by cha0s184** [comment]
It shows a number but together with some information gathered from the internet i guess.
![Screenshot_2020-05-20_18-45-23_1](https://user-images.githubusercontent.com/65662178/82473927-90b3df80-9aca-11ea-90b9-8fa6520408e9.png)

**Comment by tibbi** [comment]
are you sure it is caused by the app not being installed? Can you reproduce the glitch like that? I dont see how could it be related. Also make sure you use the latest app version 5.2.0.

**Comment by cha0s184** [comment]
I installed the latest Version today and now it looks like that.
![Screenshot_2020-05-23_17-10-00_1](https://user-images.githubusercontent.com/65662178/82734405-13cb7480-9d1b-11ea-822f-d57f782ed914.png)

**Comment by tibbi** [comment]
it isnt related to the installation date then, specific calls are invisible only. If you click on them, does the proper number get called?

**Comment by cha0s184** [comment]
Calls that where visible before are now not visible, so in some cases it is related to the date. Look at the first screenshot. Calls from May 20 where all visible and now most of them are gone. If i click on them the number gets called.

**Comment by tibbi** [comment]
ok, Ill apply a possible fix, should be working well in the next version updated soon. Reopen if it is still broken in 5.2.1. Thanks
