### ISSUE TITLE
Call history not displaying contact names

### ISSUE THREAD

**Issue by juckel** [SimpleMobileTools/Simple-Dialer#25]
In version 5.1.2 installed from the F-Droid store, I have the issue that the call history only displays the phone numbers but does not resolve it back to contact names.

**Comment by tibbi** [comment]
are the contacts stored casually under your email address, Phone, or where? What app have you used for creating them?

**Comment by abie39** [comment]
Same issue. Mine are stored under an account (not the local address book) and were created with the default contact app.

**Comment by gargamelak47** [comment]
Same issue, mine are stored in davx5 account, created and managed with simple contacts app.

**Comment by juckel** [comment]
Contact information is AFAIK stored in the default location from Android. I am using DAVx5 to sync them from my Nextcloud and work groupware instances to my phone. SimpleContacts also displays them correctly.

**Comment by tibbi** [comment]
should be fixed in 5.2.0 released soon
