### ISSUE TITLE
[Feature Request] Hide Android navigation bar when receiving/making calls

### ISSUE THREAD

**Issue by matheuswillder** [SimpleMobileTools/Simple-Dialer#257]
As the title says. Although the navigation bar is essential for navigating the app, it can become a problem when receiving or making a call, because it can be pressed accidentally.

Usually the navigation bar is hidden by default in the stock Dialer when receiving/making calls. Also, some Samsung Galaxy has an option to make a app use full screen, but it doesn't seem to work for this Dialer, so the navigation bar is always visible (Samsung Galaxy with Android 11).

![Screenshot_20211107-090359_Dialer_1](https://user-images.githubusercontent.com/46294160/140645814-6188e691-8124-415e-ac97-c26d8783920c.jpg)

**Comment by tibbi** [comment]
I dont plan hiding that, there is a proximity sensor to prevent accidental clicks
