### ISSUE TITLE
Feature Request: Add video calling (both sim)

### ISSUE THREAD

**Issue by vdbhb59** [SimpleMobileTools/Simple-Dialer#258]
Currently I cannot see any option to dial a video call. Not before, on selection or post dial or post call is picked up. This would help a lot. For me I dial my parents dialy a SIM video 2 video call. Native dialer has that support. Ideally adding to the dial pad space itself like an icon selector (HD as well) assists.

Let me know what else is needed mate and I will oblige.

Danke

FLOSSbOxIN

**Comment by tibbi** [comment]
our app has no internet access, I dont think that is doable. And it is also way out of scope of our apps.
