### ISSUE TITLE
[Feature Request] Block International Country Codes

### ISSUE THREAD

**Issue by DepecheCodeInstitute** [SimpleMobileTools/Simple-Dialer#259]
Hi there, 

Love your work! I've been getting a few pesky spam calls lately, all from international country codes, and just realised that it would be super neat if I could choose to block incoming international calls, particularly if I were able to set up exceptions (i.e block all International callers, except for two countries etc)

Thank you for your time, keep up the smashing work :)

**Comment by tibbi** [comment]
duplicate of #82
