### ISSUE TITLE
Sort favorites

### ISSUE THREAD

**Issue by Jumbo125** [SimpleMobileTools/Simple-Dialer#265]
can i sort favorites manually? i don't want it in aplhabetical order.
how can i donate the app?

**Comment by Jumbo125** [comment]
okay. i found the donate function. 
If i can order the favorties in non-alphabetical order i can use the app and will pay the donate-app.

**Comment by Jumbo125** [comment]
i see your add feautre request. So i think i can't move it. is it correct?

**Comment by tibbi** [comment]
ye, you cannot do it yet

**Comment by Jumbo125** [comment]
Thank you for your Help
Do you plane to realize it?


I hope for your answer

Best regards
Andreas

23.11.2021 11:29:55 Tibor Kaputa ***@***.***>:

**Comment by tibbi** [comment]
sure, I would have closed the issue if not

**Comment by Jumbo125** [comment]
Thank you?

**Comment by Jumbo125** [comment]
Thank you

**Comment by tibbi** [comment]
will be added in 5.13.0

**Comment by Jumbo125** [comment]
> will be added in 5.13.0

Thank you!
You are greate!!!!
