### ISSUE TITLE
Caller ID not showing for called person

### ISSUE THREAD

**Issue by SFGrenade** [SimpleMobileTools/Simple-Dialer#266]
Device: Motorola Moto G30
Apps:
Android 11
Simple Dialer 5.10.1 (F-Droid)

Steps:
1. Call person
2. Shows up as "Private number" on persons phone

Would be nice to have a setting for that.

**Comment by tibbi** [comment]
that is handled by your carrier, not our app

**Comment by SFGrenade** [comment]
Oh, the google phone app has a setting for it, so i thought this one had, too.
