### ISSUE TITLE
What makes your app able to be default dialer?

### ISSUE THREAD

**Issue by brianjmurrell** [SimpleMobileTools/Simple-Dialer#267]
I am hoping you will humour a (very) green wanna-be Android developer.  :-)

What specifically (in the [app/src/main/AndroidManifest.xml](https://github.com/SimpleMobileTools/Simple-Dialer/blob/master/app/src/main/AndroidManifest.xml), right?) allows your app to selectable as the default dialer in the Android default apps settings?

**Comment by tibbi** [comment]
Im not fully sure which line does it now, could be the ANSWER_PHONE_CALLS permission or the DEFAULT intent for Call action at https://github.com/SimpleMobileTools/Simple-Dialer/blob/master/app/src/main/AndroidManifest.xml#L127

**Comment by brianjmurrell** [comment]
Hah!  I'm close.  My dialer now shows up as an app that I can set as the default dialer.  But still unlike yours, even when mine is set to be the default dialer, asking Google Assistant to "call <number>" it still wants to use the system default dialer.

So you still have some magic in yours that is allowing Google Assistant to use it that I don't have in mine.  I'll keep trying.  But if you know what that specific bit is, you could save me some time.  :smile:

**Comment by tibbi** [comment]
just check in Android Studio Logcat what intent is triggered at the "call" action
