### ISSUE TITLE
Swipe right to make a call, left to send a message

### ISSUE THREAD

**Issue by gdnzz** [SimpleMobileTools/Simple-Dialer#272]
Samsung's dialer has that type of design. When you swipe right on a contact, it makes a call; when you swipe left, it sends a message. I think it is very intuitive and modern; it would be nice to see it. Here is a demonstration of it:
https://yewtu.be/watch?v=FeJdmATkABY

**Comment by tibbi** [comment]
that isnt on the roadmap, sounds weird
