### ISSUE TITLE
The number of missing calls is always counted of one more

### ISSUE THREAD

**Issue by MR-Diamond** [SimpleMobileTools/Simple-Dialer#275]
I am using last version (5.11.1) of Simple-Dialer from F-Droid.
I am on Android 11.

What happen: when I miss one call, Simple-Dialer reports the notification of two missing calls; if I have two missed calls, the notification reports three missing calls, and so on: the missing calls are always reported as +1.
If I open the app, instead, the number of missing calls in the history tab is right: this happen only in the notification of Simple-Dialer.

EDIT: when using the default dialer (Google Dialer) this behaviour doesn't happen.

**Comment by Aga-C** [comment]
It's already reported here: https://github.com/SimpleMobileTools/Simple-Dialer/issues/256
