### ISSUE TITLE
take incoming call without unlock

### ISSUE THREAD

**Issue by Jumbo125** [SimpleMobileTools/Simple-Dialer#277]
Is it possible to take a incoming call, without unlock screen before?

i need to unlock my lock screen, before i can pick up the call.
is there any solution?

Thank you

**Comment by tibbi** [comment]
sure, it should work like that already, the call screen should be shown even on a locked device so you can accept/decline the call. If it doesnt show up you might have some extra security enabled in your device settings

**Comment by Jumbo125** [comment]
Okay.. I already get the call on the Lockscreen. 
But to use the pick up button, I need to unlock before

**Comment by tibbi** [comment]
you shouldnt need to. It must be some device or system specific issue though, the app is handling it well

**Comment by Jumbo125** [comment]
Okay
You are great!!!
