### ISSUE TITLE
accept call onlz with swipe

### ISSUE THREAD

**Issue by Jumbo125** [SimpleMobileTools/Simple-Dialer#283]
My wife has the same phone like me. 
I paid your products to. 
If I take a call to her, she need to sipwe to right or left. I can press the button to receive the call. 
How can I disable swipe on the phone from my wife?
I want to press the button to accept like me

**Comment by tibbi** [comment]
clicking has been exchanged for swiping in the latest app version, you cannot customize it yet.

**Comment by Jumbo125** [comment]
Thank you
