### ISSUE TITLE
Default dialer

### ISSUE THREAD

**Issue by ErinVoid** [SimpleMobileTools/Simple-Dialer#29]
Simple-Dialer is set as the default dialer in the phone's "App" options. However, whenever trying to use it to dial, the phone asks if Simple-Contacts should be the default dialer. If you cancel, you go back to dialer, if "Set Default" it goes though the usual steps to make a call. However, Simple-Contacts is not set as default and the question is asked for each usage. 
SC - 6.10.2 (Fdroid)
SD - 5.2.0 (Fdroid)
Android - 9

Appreciate Dialer is new but cannot see any options in the phone's settings or the software to alter the behaviour.

**Comment by tibbi** [comment]
Simple Contacts will lose its calling capabilities within the next few days, only Dialer will be used for that purpose. So Ill close this. Thanks
