### ISSUE TITLE
go back to first call and close it - fail

### ISSUE THREAD

**Issue by Jumbo125** [SimpleMobileTools/Simple-Dialer#294]
Hello 
I think i have an issue.
If i have a call and get a new incoming call, i can pick up the call. This works perfect. The old call get the info "hold the line". This is also perfect!
When i have finished the new incoming call and hang up the call, i go back to the old call and can continue my old call. Perfect!

All function works. BUT if i have finished my "first" call i can't hang up the call.

Do you have any idea?

**Comment by Aga-C** [comment]
Is it the same as #290?

**Comment by tibbi** [comment]
ye
