### ISSUE TITLE
Dialer Stopped Dialing

### ISSUE THREAD

**Issue by TiresOfItAll** [SimpleMobileTools/Simple-Dialer#295]
After experiencing problems reverting to ongoing calls with Dialer (another topic) I reinstated the default Google Phone app (Android 9).  I later changed the default to Dialer again but it doesn't dial.  It does everything except dial.  I uninstalled and reinstalled it to no avail.  The ThankYou app remains.  Dialer does not perform outbound calls.  The apps default shows Dialer as default.  Short of a phone reset that I am not interested in doing (lots of supposedly secure apps I would have to reinitialise) is there any way to debug or 'kick' Dialer back into operation?  For now Google Phone is it :(

**Comment by tibbi** [comment]
check the app in your device settings and grant it all permissions + make it the default app for handling calls

**Comment by TiresOfItAll** [comment]
None of those.  Confirmed as default and all permissions applied.  An attempt to dial gets a quick 'jingle' tone and as often as not shows a call in progress i cannot hang up, but the call does not seem to have happened.  Is there a log I can look at?

**Comment by tibbi** [comment]
not really, try restarting your device. Guess some of those security apps broke it, doesnt sound like an issue on our side.
