### ISSUE TITLE
Ringtone isnt working

### ISSUE THREAD

**Issue by themighty1** [SimpleMobileTools/Simple-Dialer#304]
Hi, Im using the latest version 5.11.3 on a non-rooted phone with Android 8.1.0
The app has all the permissions.
On an incoming call the ringtone is NOT playing.
When I switch to the stock Dialer, the ringtone plays. When I switch to Simple Dialer, there is no sound.
I also tried another 3rd party dialer "True Phone Dialer" and it DOES play the ringtone. 

Maybe would be good to allow to select the ringtone from within the app?

Thanks.

**Comment by tibbi** [comment]
It is handled by the system, not us. You mean that nothing rings at all, or is it just about some contact specific ringtone?
