### ISSUE TITLE
Feature Request: Add video call support just like google dialer

### ISSUE THREAD

**Issue by dtbj** [SimpleMobileTools/Simple-Dialer#306]
Feature Request: Add video call support just like google dialer

**Comment by tibbi** [comment]
the app has no internet access so dont expect having it

**Comment by dtbj** [comment]
@tibbi Ok fine but you can use internet no users have problem.

**Comment by dtbj** [comment]
I guess it would be great feature I am not talking about google duo type video calling I am talking about carrier video calling if you take it wrong. The carrier video call works offline :-)

**Comment by tibbi** [comment]
maybe, but dont expect such an advanced feature anyway

**Comment by dtbj** [comment]
@tibbi OK no issues thanks for your reply.
