### ISSUE TITLE
Hands-free calling/talking does not work

### ISSUE THREAD

**Issue by genodeftest** [SimpleMobileTools/Simple-Dialer#31]
From the user interface, I guess that the loudspeaker symbol should toggle *hands-free talking*.

Steps to reproduce:
1. Start a phone call
2. Toggle the *loudspeaker* symbol

What happens:
* The loudspeaker symbol changes
* Output does not change between speakers.

What should happen:
* When toggling hands-free calling, the sound should toggle between the ear-speaker and the loudspeaker for 

Version info:
5.2.0

Additional info:
This works fine with the official phone app, `com.google.android.dialer`, currently available in version 48.0.x on my Android 9 patchlevel 2020-04-01.

I am able to extract an adb log if you tell me what to look for.

**Comment by genodeftest** [comment]
Works fine now in version 5.4.0. Thank you!

**Comment by tibbi** [comment]
you sure? I havent done anything to it. Maybe it depends on something else then.

**Comment by genodeftest** [comment]
Yes, I am sure it works fine for me (I've been using it for a while). You may be right that it depends on something else though…
