### ISSUE TITLE
(BUG) Dialer does not show names only numbers

### ISSUE THREAD

**Issue by Fehertukor** [SimpleMobileTools/Simple-Dialer#311]
Hi!
Thank you again for your work I love your apps!

I just got this bug that my private contacts only shows phone numbers not the name in dialer app.
Everything looks OK in simple contacts(I can see names there).
 I use private numbers and they forced to appear in dialer. 
It worked flawlessly but i got this but recently.
It seems that the dialer lost the contact with the contacts app and that is why can't show private numbers name.
(I have reseted both dialer and contacts; phone restart did not help.)

Android 11
OxygenOS

Thanks you!

**Comment by tibbi** [comment]
what app versions are you using?

**Comment by Fehertukor** [comment]
Dialer version 5.11.3
Contacts version 6.17.1

**Comment by Aga-C** [comment]
The latest version of Simple Dialer 5.11.4 fixes this issue.

**Comment by Fehertukor** [comment]
Thanks!:)

**Comment by alessiom72** [comment]
Hi!
I have the same problem. I use Simple Dialer 5.17.5 and Simple Contacs Pro SE 6.22.2.1 on Android 12.

PS. I love your apps. Thank you very much for them.
