### ISSUE TITLE
Incoming call popup

### ISSUE THREAD

**Issue by mi007d** [SimpleMobileTools/Simple-Dialer#314]
![slim-down-incoming-call-alerts-android-tiny-lollipop-style-popup 1280x600](https://user-images.githubusercontent.com/100167438/155423326-b66bde87-8468-41c0-91e2-6447cc8cf328.jpg)

Sometimes we are playing or watching a video and the call screen appears, it could be replaced by a popup (like the image above)

**Comment by Aga-C** [comment]
It's already reported here: https://github.com/SimpleMobileTools/Simple-Dialer/issues/140.
