### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by Krawei** [SimpleMobileTools/Simple-Dialer#318]
Dear Devs,

when I click on the app symbol in my app drawer, the app shows me the contact list for a short glimpse of time and then crashes immediatly.

I checked the app's permissions and accu/battery configurations and deleted its' cache and data and re-installed it - but nothing worked so far,

I issued a logcat via the adb and hope you can find any bugs or fails in it. You'll find the link to it here:

https://bin.tiekoetter.com/?e9b636beda1881d1#uEYSztr1LriqFbAGxveVvbk3wA2VkDUepiShRxUH5Mz 

Basic Data:

Device: Realme 7 Pro
OS: Android 11
Security patch: February 5th, 2022
Android Distribution: Realme UI 2.0 (fork of Oppo's ColorOS)

Hint: The App works via the widget "dial pad" where I can type a number directly. But there's no access to the call log or "directly" mentioned above.

Thanks for your great work!

Kind Regards,

G.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by Krawei** [comment]
Installed app's version is 5.11.4 from F-Droid.

**Comment by tibbi** [comment]
right, will take a look at it

**Comment by Krawei** [comment]
Update: The Problem persists with the F-Droid-Version 5.11.5.

In addition I use my Realme 7 Pro with a dual-sim setup. Maybe this triggers the problem?

**Comment by tibbi** [comment]
not sure, try removing a sim card

**Comment by tibbi** [comment]
retry with 5.12.0 released soon, a related crash will be fixed
