### ISSUE TITLE
Silent dial pad

### ISSUE THREAD

**Issue by heydojo** [SimpleMobileTools/Simple-Dialer#325]
Hi, for better accessibility I would love to see the Android "Dial pad tones" setting respected. Currently, the setting found in Android's advanced sound settings does not effect Simple Dialer. As there are currently no number tones played at all when a number is entered into the dial pad. Dial tones allow people with poor vision to more easily enter numbers into the handset. I don't know if this is a bug or a missing feature.

Otherwise a great app. Keep up the good work! Thanks!

**Comment by tibbi** [comment]
you will be able to toggle it in 5.15.0
