### ISSUE TITLE
In the recent calls list, please show the time of the call alongside the date

### ISSUE THREAD

**Issue by watttman** [SimpleMobileTools/Simple-Dialer#332]
I am running 5.12.0 installed at Motorola one 5g Ace (Android 11) installed from Play Store.
For me the time of calls in call log is important, and I have disabled "group subsequent calls with the same number at the call log" option.
Please show the time of the call alongside the date (for days prior than "today"), there is no reason to hide this when the"group calls" option is disabled.
Thank you for the SimpleMobile tools suite!

**Comment by tibbi** [comment]
you can see those details if you long press the wanted item and use the top Menu -> Show call details
