### ISSUE TITLE
The screen becomes black when the notification-shade is invoked during communication.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [SimpleMobileTools/Simple-Dialer#334]
This may be relevant to "http://github.com/SimpleMobileTools/Simple-Dialer/issues/330".

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I am able to record the problem if that is desirable, especially if it does not affect anybody else.

**Comment by tibbi** [comment]
that is caused by the proximity sensor indeed

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Was this issue closed because @tibbi considers it to be duplicatory, or because the problem was remediated?

**Comment by tibbi** [comment]
it will be fixed with #330

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@tibbi, #330 shall not remediate this problem, because if I press the home button without enabling the speaker-button, the problem shall continue even if what #330 requests is implemented, because this problem affects the phone specifically during observation of the notification-shade. The problem does not occur for me unless I invoke the notification-shade.
