### ISSUE TITLE
Remove the ability to display contacts.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [SimpleMobileTools/Simple-Dialer#335]
I have been unable to understand why it is included if Simple Contacts already provides its abilities. Obviously disablement of the tab negates this problem for me, but inclusion of it wastes space unless it reuses code from the dedicated application.

**Comment by tibbi** [comment]
what contacts you mean?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@tibbi,
![Screenshot_20220504-131531_Dialer](https://user-images.githubusercontent.com/42837531/166679267-8587eae8-2615-427c-834b-3aa14c702d7b.png)
![Screenshot_20220504-131452_Dialer](https://user-images.githubusercontent.com/42837531/166679271-4058d7a3-c39e-48b5-ae76-ec3ca47c2c9c.png)
is what I refer to.

**Comment by tibbi** [comment]
I still dont know what you mean. History tab shouldnt be shown? Thats how it works to me, try reenabling everything, then disabling the unwanted ones

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I mean that the ability to display contacts should ve removed, because that is what the Contacts app exists for.

**Comment by tibbi** [comment]
why wouldnt a dialer show contacts? It has to

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@tibbi, why must it?
