### ISSUE TITLE
No calls received when screen is locked

### ISSUE THREAD

**Issue by freebrowser1** [SimpleMobileTools/Simple-Dialer#352]
When the screen is locked and someone calls me, the caller gets an occupied tome while my phone dues wake up, but no green and red pickup buttons appear. So actually I cannot be called when the screen is locked. When unlocked, everything works normally.
So I reverted to the default phone app which can receive calls when unlocked, but picking up calls with the default app is somewhat clunky.
Can this be fixed ?

Oneplus 6, Android 10 stock ROM.

**Comment by tibbi** [comment]
should be fixed in 5.13.0 already
