### ISSUE TITLE
suggestions while dialing

### ISSUE THREAD

**Issue by andsofine** [SimpleMobileTools/Simple-Dialer#364]
when entering the (first digit) number, add a suggestion to create a new contact or add to an existing one 

when entering asterisks and hash marks (on their own/without digits) this should not be suggested 

https://user-images.githubusercontent.com/99369164/170860883-4877d752-3611-487f-8073-bc47da327276.mp4

and remove the add contacts button from the bottom right, as it will be a duplicate

**Comment by tibbi** [comment]
thats not even our app

**Comment by andsofine** [comment]
> thats not even our app

this is just an example

how can I show a function in your app that does not exist in your app?
