### ISSUE TITLE
move inscriptions to center

### ISSUE THREAD

**Issue by andsofine** [SimpleMobileTools/Simple-Dialer#365]
move to the center such inscriptions as::
Could not access your contacts
Request access;
Could no access your contacts;
Could not access the call history
Request access;
No contacts found
Create new;
No contacts found

maybe I missed some and did not write out everything

in general, this must be done because it's inconvenient to reach the top to press request access or something else
and also because now the middle looks empty
![Screenshot_20220529-131822](https://user-images.githubusercontent.com/99369164/170863107-a6a2bd54-31ab-42e3-bb17-4777ea667379.png)

**Comment by tibbi** [comment]
I want to keep it there at the top now
