### ISSUE TITLE
Text in dial screen isn't shown correctly in RTL

### ISSUE THREAD

**Issue by mhmdanas** [SimpleMobileTools/Simple-Dialer#373]
When using an RTL language, the text in the dial screen is at the far left of the screen, with much of it clipped:
<img src="https://user-images.githubusercontent.com/32234660/173070662-3028bff3-4f28-48df-86f2-2f44fd5879e3.png" height=500> <img src=https://user-images.githubusercontent.com/32234660/173070667-f47eb7d0-46f4-4a17-91e6-acc42789aed3.png height=500>

**Comment by tibbi** [comment]
will be fixed in 5.15.0
