### ISSUE TITLE
Feature Request: Option for Persistent Voice Mail Notification

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/Simple-Dialer#38]
I accidentally dismissed the voice-mail notification and was unable to recall it until after a device reboot.

**Comment by tibbi** [comment]
duplicate of #23

**Comment by Saijin-Naib** [comment]
Are the in-call and voice mail waiting both the same?

**Comment by tibbi** [comment]
I dont know, not really differentiating between any of those

**Comment by Saijin-Naib** [comment]
Issue #23 is about the in-call (you actually having an open phone call), and this issue is about your voicemail notification (not being in a call).
