### ISSUE TITLE
Sort Contacts by Surname

### ISSUE THREAD

**Issue by mike-lloyd03** [SimpleMobileTools/Simple-Dialer#383]
Thanks for the clean and simple dialer. Can you add an option to sort by surname just like in the contacts app?

Thanks!

**Comment by Aga-C** [comment]
It's already added.

**Comment by mike-lloyd03** [comment]
It doesn't look like this feature has been implemented. I can only sort contacts by Full Name or Date Created. I see a setting where I can put surname first but this isn't ideal. I would like to display first name first but sort by surname. Simple Contacts allows this. 

Simple Dialer:
![Screenshot_20230328-065244_1.png](https://user-images.githubusercontent.com/49411532/228262288-7cc75ace-4d6f-4e15-8beb-5994eedbeb38.png)



Simple Contacts:
![Screenshot_20230328-065146_1.png](https://user-images.githubusercontent.com/49411532/228262243-14b1f90f-4b74-41a4-8705-af1bace60e70.png)

**Comment by tibbi** [comment]
will be added in 5.17.5, the previous versions rollout has been stopped to fix some glitches
