### ISSUE TITLE
Empty call history

### ISSUE THREAD

**Issue by Saturdaynightlife** [SimpleMobileTools/Simple-Dialer#388]
I like the idea behind simple tools and use them as an reliable alternative to google apps. Of course I donated already and hope that the work of Tibur Kaputa goes on.

While using simple dialer it took more and more time to display/build up call history when switching to 'recent calls'.  At the Moment this took almost 2 Minutes! I could delete call history to speed up display of the list but I like to know who called me when even months ago.

Is there a chance to fix this bug?

**Comment by tibbi** [comment]
You can use the Clear call history at the top menu for that. Limiting it to 50 entries has been added in the latest app version, so it should be quicker by default too.
