### ISSUE TITLE
Bug: Unable to navigate back to incoming call after pressing back button

### ISSUE THREAD

**Issue by RafeeDaBoy** [SimpleMobileTools/Simple-Dialer#397]
Issue: When a call is incoming and I press the back button and unlock the phone. The call is still going on and the phone is ringing, but there is no way to open the call screen again. Trying to initiate a call shows a message "call not sent".

Expected feature(?): After the unlocking the phone, navigating back to the call screen from the notification panel.

**Comment by tibbi** [comment]
What app and OS version are you using?

**Comment by RafeeDaBoy** [comment]
Android version: 11
SimpleDialer version: 5.13.3
