### ISSUE TITLE
Feature Request: Option for disabling incoming call top notification

### ISSUE THREAD

**Issue by McNinjaTNT** [SimpleMobileTools/Simple-Dialer#399]
As of 5.13.0, incoming calls show up as a top notification instead of taking up the entire screen. This can be problematic as, especially for old people, it's more confusing. An option to force full screen incoming calls instead of using a notification would be very nice.

Note: This only happens when the phone is already unlocked

**Comment by lefterisgar** [comment]
Yes, I agree that this is very important for older people. They just don't care that their phone can do multi-tasking.
