### ISSUE TITLE
Bug and Feature  request

### ISSUE THREAD

**Issue by qw123wh** [SimpleMobileTools/Simple-Dialer#4]
Hello thanks for your work, I use many of your apps and I like them very much.  I mainly use your app's simple contacts and very nice simple text messages and they work well.  However, I tried simple dialer, I understand that it is the first version and it is a bit immature and it will certainly improve with time, but today there are many things that are wrong, I tell you first what I think are bugs for me.  And then I'll make some requests. I apologize in advance if I will be too "bad", please do not be offended I just want this app to be better and that it can be on par or even superior to all the other existing android dialer apps. 
I believe in you and I believe very much in your projects and in your work.

Bug?

The things you should improve example when I receive a missed call the notification arrives on the system dialer and not on simple dialer despite having put it as the default dialer and the same thing happens for blocked calls the notification appears on the system dialer or even on  another dialer installed but I don't get notification about simple dialer.  These are bugs for me because any other dialer when set to default sends notifications of missed calls or blocked calls (if it also has that function), while in simple dialer the missed calls are displayed in the call log but without notification or other.  It's as if it's leaning on other app dialers.

As for the functions that I would like to be implemented 

I would like the home page to be the calls page and not the contacts page, put an option to let the user choose

Delete single call from the call log

For example if I want to delete only one entry from the call log example I call "john" 10 times I want to delete only the last 2 calls to John I can't do it because it makes me delete all 10 calls

When i receive a call from an unsaved spam number i would like the add to blacklist item to be added without having to manually copy the number to be added to the blacklist.  

When I click a contact in recent calls, I would like the call not to start immediately, but the possibility to call or send a message or show the call history, or add to blacklist

For the duration of the calls I would like to add m or min for minutes and s or sec for seconds and h or hou for hours 
Example 8 seconds now 00.08 appears while I would like 8 s or 8 sec to appear, same thing for minutes and hours.  Because for example I use 24 hours and if I make a call at 19:12 that lasts 18 minutes and 15 seconds I see 19:12 and 18:15 and I don't understand anything while I saw 19:12 and 18 min 15 sec or 18 m 15  s then I understand

**Comment by tibbi** [comment]
Hey, please create 1 issue per request, it cannot be handled like this
