### ISSUE TITLE
Time on call details show extra digits

### ISSUE THREAD

**Issue by AalmanMohd** [SimpleMobileTools/Simple-Dialer#401]
![IMG_20220712_125101.jpg](https://user-images.githubusercontent.com/96546470/178432614-6af763ba-a6fc-41f5-8a1b-34ccb6b84cfc.jpg)

Some call details show 4 digits in the minute part of call time instead of just 2

**Comment by tibbi** [comment]
it is the duration that should be on the right side. It has been fixed already, just needs an app update.
