### ISSUE TITLE
feature request: block unknown numbers, contact list as allow-list and hide caller id

### ISSUE THREAD

**Issue by foolioo** [SimpleMobileTools/Simple-Dialer#402]
Firstly, **THANK YOU** for the fine work on all of your apps.
I am experiencing no issues with Simple Dialer and I love the app.

It would very helpful if Simple Dialer would have the functionality to:
1. Block unknown/private numbers, in the same spirit as [Google Phone, Galaxy Dialer and others](https://www.howtogeek.com/775028/how-to-block-unknown-numbers-on-android/)
2. Block any number that is not in the contact list. This will treat the contact list as a an allow-list.
3. Hide the caller ID when making a call to a number that is not in the contact list, in the same spirit of [CallerId Blocker](https://apkfab.com/callerid-blocker/com.nosapps.android.callerid) (which cannot be found on Google Play) (for more information about GSM codes, see https://www.geckobeach.com/cellular/secrets/gsmcodes.php)

Thanks!

**Comment by tibbi** [comment]
hi, report things one by one please. Regarding 2., it has already been added on Android 7+
