### ISSUE TITLE
DUAL SIM: All card icons are labeled as "2"

### ISSUE THREAD

**Issue by qazip** [SimpleMobileTools/Simple-Dialer#41]
I have a dual sim phone and every entry in the Dialer is labeled with the icon pertaining to the 2nd SIM card, which is wrong. Some calls are for/from the 1st SIM card, others from the 2nd SIM card.

**Comment by tibbi** [comment]
does it work well in some other downloaded Dialer app? I mean a downloaded one, not preinstalled.

**Comment by qazip** [comment]
> does it work well in some other downloaded Dialer app? I mean a downloaded one, not preinstalled.

I haven't tried yet. I know it works well on the default (Phone, by google) app.

**Comment by karferz** [comment]
Hi, I also have the same issue with my Xperia 10 II stock ROM with Android 10. I didn't tried other app because all required that you have to upload you contacts and I'm not agreed with that.

**Comment by cramer52** [comment]
Hi, I also have the same issue on my Xiaomi Mi 10 Pro Android 10 (Miui 12 Eu). On the google dialer (downloaded) it is working fine. Anything new regarding that issue? Thank you in advance.

**Comment by morrogenduath** [comment]
I have the same issue on Wileyfox Spark X, Android 7.0, Simple Dialer v5.5.1

**Comment by alekksander** [comment]
Confirm on 5.5.3

**Comment by morrogenduath** [comment]
This is still present in v5.8.0

**Comment by amalgame21** [comment]
I cannot find any downloaded Dialer app that can display two different sim slot.
I tries kolar and emerald dialer, both are mixing both sim slot call log, with no indication of different sim slot.
do you have any recommondation for us to test it out?

**Comment by tibbi** [comment]
Im not sure. Maybe they are trying to detect 2 sims, but while we show "2" as the default, they just do not show any SIM icon at all.
