### ISSUE TITLE
feature request: calls from favourite contacts only

### ISSUE THREAD

**Issue by n00bus** [SimpleMobileTools/Simple-Dialer#411]
I use contacts-only mode on daily basis (i used NoPhoneSpam for that before (but it has an issue - phone alarm starts anyway), but now i don't need it anymore in most cases). It makes my life much easier without those spam calls. But sometimes in vocations it would be nice to have more narrow list of accepted calls (in roaming especially) like favourites-only calls.
Not sure if anyone will support this idea, but it's an alternative limited support of a white list.
All the rest goes to the electronic secretary with recording and speech recognition (separate topic, it's necessary just to decline a call).

**Comment by n00bus** [comment]
As an enhancement of this - choosing accepted groups. But not sure if SimpleDialer can stay that simple in that case.

**Comment by tibbi** [comment]
that is too advanced, dont really expect having it
