### ISSUE TITLE
feature request: call log export

### ISSUE THREAD

**Issue by tondy67** [SimpleMobileTools/Simple-Dialer#412]
It would be great if there is an option to export the calls log :)

**Comment by tondy67** [comment]
And that of course :)
I meant import/export of call logs. The user can change devices or mobile operators but this information must be saved somewhere...

**Comment by sudwhiwdh** [comment]
Does "call logs" here mean the contents of the "Call History" tab?

@tibbi Where can I open issues that affect all SimpleMobileTools at the same time?

**Comment by sudwhiwdh** [comment]
Does "call logs" here mean the contents of the "Call History" tab?

**Comment by tondy67** [comment]
Yes,   time, duration, phone number ... exported to csv or json :)

**Comment by nuraiman** [comment]
It's useful also when you accidentally cancel the history
