### ISSUE TITLE
Animated arrows in dial screen are flipped in RTL

### ISSUE THREAD

**Issue by mhmdanas** [SimpleMobileTools/Simple-Dialer#415]
Apologies for sending a screenshot instead of a screen recording, I removed some packages from my system and now I can't find the record button anymore...

![Bug screenshot](https://user-images.githubusercontent.com/32234660/181358894-a511e1ee-905a-42c7-816c-92121492cc5c.png)

**Comment by tibbi** [comment]
will be fixed in 5.15.0
