### ISSUE TITLE
Incoming calls

### ISSUE THREAD

**Issue by sebasarena** [SimpleMobileTools/Simple-Dialer#419]
The app doesn't show a full screen notification of an incoming call.

Last year the app did it without problems. But now it only show a minor notification not even noticeable.

So all my incoming calls becomes missed calls.

App version 5.14.0
Android 11
No root

**Comment by tibbi** [comment]
is your screen on when the call arrives?

**Comment by sebasarena** [comment]
> @sebasarena did you allow the app to [draw on top of other apps](https://ssiddique.info/draw-over-other-apps-display-over-apps-on-android.html)?

Yes, I gave it permission to show information on top of other apps.

**Comment by sebasarena** [comment]
> is your screen on when the call arrives?

Yes, the screen is on and unlocked most of the times that I receive a call.

**Comment by josefson** [comment]
On a similar note, when my screen is blocked it rings but nothing really happens, no option to take the call, even if I unblock the phone and enter the home screen there's nowhere to answer the ringing call.

**Comment by tibbi** [comment]
right, on unlocked devices there is only a notification. A toggle for always showing fullscreen alert will be added in the next app version released soon.

**Comment by lucamp** [comment]
With new release 5.15.3 pop-up for incoming calls are not dispayed anymore.
Users have to swipe down the notification panel to answer the call

Android 10

**Comment by tibbi** [comment]
will keep an eye on it, it might depend on the priority of other notifications.

**Comment by sebasarena** [comment]
> 

I guess that «lucamp» is using the version of F-Droid, as myself: https://f-droid.org/es/packages/com.simplemobiletools.dialer/

Their team have released 5.15.4 version recently. 

What do you recommend? Stop using the F-Droid app?

**Comment by tibbi** [comment]
5.15.4 has been added just recently indeed. That app is updated by me and it is the same as on Google Play, no nee to worry about that

**Comment by sebasarena** [comment]
Oh sorry, I didn't check the releases here in GitHub.

Glad to know that you are in charge of the F-Droid version too!
