### ISSUE TITLE
control numpad key press vibration feedback

### ISSUE THREAD

**Issue by foolioo** [SimpleMobileTools/Simple-Dialer#420]
when typing a number using the numpad, each key press has a vibration feedback even when the phone settings explicitly disables vibrations for key presses.

the issue does not exist in other phone/dialer apps.
i am using simple dialer version 5.14.0 and android 11 (and android 8 on other phone).

is there anyway to disable the key press vibration feedback? it is the default behavior?

**Comment by tibbi** [comment]
you will be able to toggle it in 5.15.0
