### ISSUE TITLE
call history: the caller's name is shown, but which of his numbers did he use?

### ISSUE THREAD

**Issue by ihaake** [SimpleMobileTools/Simple-Dialer#43]
There should be a hint which of his numbers a contact did use for a certain call: 
mobile/private/work/...

**Comment by tibbi** [comment]
showing the number on the call screen is on the roadmap

**Comment by tibbi** [comment]
label will be added in 5.12.0. If you want to see the exact number you have to go to "Show call details", I dont want to flood the call log too much by default
