### ISSUE TITLE
Feature Request: Please show the time of calling in the next day

### ISSUE THREAD

**Issue by Raj2032** [SimpleMobileTools/Simple-Dialer#456]
I am so far liking this app but I can't completely replace this app yet

![image](https://user-images.githubusercontent.com/29293830/192134179-670ffa38-fdea-451d-9f2e-17091180f172.png)

Unfortunately when the next day comes, then the call history time is hidden. Please show the call history time as well as I would like to see what time did they call as well like on other phone calling apps, thank you!

**Comment by tibbi** [comment]
you can check it at the View call details

**Comment by Raj2032** [comment]
@tibbi Yes but like in the previous phone app I used to use, I would like to see it all shown in front of me, as that would be tedious to go through every single call history to find the right time.

**Comment by tibbi** [comment]
I dont want to flood the screen with so much unnecessary stuff

**Comment by Raj2032** [comment]
@tibbi What if it was done like this like in the samsung calling app:

![image](https://user-images.githubusercontent.com/29293830/192229459-3c28bd57-c549-4efc-9e5e-7a68ae75d1a7.png)

See how there is a top heading for the date/day and inside the heading there are individual times? Wouldn't this be clutter free and easier to find what you are looking for?

**Comment by tibbi** [comment]
that isnt planned, doesnt make much sense
