### ISSUE TITLE
Feature Request - Allow Initiation of Signal Call for Signal Contacts

### ISSUE THREAD

**Issue by shrimprugbysnowowl** [SimpleMobileTools/Simple-Dialer#458]
I checked through the open and closed issues and didn't see this brought up, so apologies in advance if this has already been hashed out.

When a contact is called from the default dialer for CalyxOS, a dialog box appears which gives the user a choice to initiate the call through the wireless network provider or the Signal network, if available. It might be useful to incorporate such a feature in Simple Dialer, if possible, and the feature could be enabled/disabled in the settings.

Dialog box shown by CalyxOS default dialer:
![Screenshot_20221006-215611](https://user-images.githubusercontent.com/59341190/194458537-d74e0574-af6a-4c8a-8f01-bf23daf1fbc0.png)

Thanks for the consideration

**Comment by marc0x1** [comment]
would be great! It would also be useful to use telegram as a backup
