### ISSUE TITLE
Layouts on tiny screens

### ISSUE THREAD

**Issue by sphh** [SimpleMobileTools/Simple-Dialer#460]
Thanks for the Dialer!

I use it on a Unihertz Jelly Pro, with a tiny screen: 240×432px. There are two tiny problems:

### Dialpad

Dialer vs. Phone
![Screenshot_20221010-101259](https://user-images.githubusercontent.com/4856462/194829507-9a03bbf8-f35c-47e3-9507-da852284f93a.png) ![Screenshot_20221010-105257](https://user-images.githubusercontent.com/4856462/194830148-267cb863-aff9-47a8-8c4d-b3f4263591e4.png)
As can be seen, the list with the (filtered) contacts is not visible in the Dialer. May I suggest to remove the "← Dialpad  +" header on such tiny screens (the "+" could be moved to the bottom?) and shrink the pad a bit by removing the spacing between the keys. It would be great, if at least 3 contacts could be made visible!

### Ongoing call screen

![Screenshot_20221010-101423](https://user-images.githubusercontent.com/4856462/194831301-0b6d6127-b326-4fe4-91a8-14b4da72b20b.png)

As you can see, the row with the SIM card used and the call status overlaps with the control buttons, whereas there is a lot of free space available above the name. Also the space between the control buttons and between the block with the control buttons and the hang-up button are not the same, resulting in an unbalanced impression …

**Comment by tibbi** [comment]
should be better in 5.17.0

**Comment by sphh** [comment]
Thanks!

Re. the dialpad: Now I can see as many numbers as in the Phone app: 1½ rows. That's great, thanks. Is it possible to disable the icon on the left side, so that I can see at least two rows (and if lucky 2½ rows)?

Re. the ongoing call screen: Has there been any changes? On my phone the row with the sim card and the status are still overlapping the first row of icons …

**Comment by tibbi** [comment]
will keep an eye on that
