### ISSUE TITLE
Missed calls are counted twice in the notifications if a full screen call was displayed

### ISSUE THREAD

**Issue by raincons** [SimpleMobileTools/Simple-Dialer#462]
Thanks for the best apps!

Each missed call in the system notification is counted twice. If one call is missed, system notifications say "2 missed calls", if 2 then "4 missed calls", etc..
If "Always display incoming calls on full screen" is disabled, the number of missed calls in notifications is considered correctly.

- Dialer 5.15.4 set as default phone app
- Lineageos 18.1 (Android 11)
- dual sim

**Comment by tibbi** [comment]
that likely isnt related to that setting, can you double check it?

**Comment by rainberd** [comment]
I checked again. Correction:
missed calls are counted twice if a full screen call was displayed. In any case, this setting was enabled or the phone was locked and asleep.
Check also on another phone with android 6, the problem is not reproduced.

**Comment by rainberd** [comment]
Update.
Also, when using Simple Dialer, these calls are duplicated for other applications that use the call log. For example, a screenshot of a call log export by a third-party application.
![screen](https://user-images.githubusercontent.com/76438224/195824963-407ea3dd-6799-4cb8-8aab-d535516dc578.png)

**Comment by tibbi** [comment]
I dont know what does that mean, like the call end is triggered 2 times?

**Comment by pudup** [comment]
> I dont know what does that mean, like the call end is triggered 2 times?

I too have this issue on android 12

The notification from the app says twice the amount of missed calls. Having one missed call results in a notification that says I have two missed calls. Having two missed calls gives a notification saying I have four missed calls and so on.

**Comment by pudup** [comment]
It seems the call is recorded twice even if it's not missed. It doesn't show on the app itself but if another dialer is installed, any received call is shown has being received twice even if picked up. One 10 minute call shows up as 2 separate calls both 10 mintues long and at the same time.

**Comment by knobhead** [comment]
I can confirm this for 
Version 5.17.3
Lineage OS 19.1 (Android 12)
Fairphone 3
Simple Dialer as Default phone app (don't think I can disable/uninstall the default OS dialer app).

**Comment by raincons** [comment]
I found a solution. Please check https://github.com/SimpleMobileTools/Simple-Dialer/pull/549
