### ISSUE TITLE
Bug:always prompts me to set as default phone

### ISSUE THREAD

**Issue by SteveZMTstudios** [SimpleMobileTools/Simple-Dialer#464]
![Screenshot_2022-10-15-17-59-04](https://user-images.githubusercontent.com/98326195/195980895-1014baff-ef46-469d-b581-35a528f16af9.png)

When I try to dial, the program always prompts me to set the simple dialer as the default phone, but even after I have set it up and provided enough permissions, it still does not work.
![Screenshot_2022-10-15-17-58-42](https://user-images.githubusercontent.com/98326195/195980899-67582bc7-24cb-4bd8-b3a6-f5b6cc3928a1.png)
![Screenshot_2022-10-15-18-01-01](https://user-images.githubusercontent.com/98326195/195980913-75a56036-e1ee-4418-88f7-cfc3b4948974.png)
I'm using Huawei Honor's Android 6.0.1 emui4.0.3, maybe that's the problem? But I can't find a firmware package that can be updated or a supported lineage OS on any platform. This device is rooted and flashed to the magisk platform, but it doesn't seem to support xposed and riru.

There may be some minor description issues(such as grammar) as I am struggling to learn English.

**Comment by tibbi** [comment]
you have way too many system customizations, it is hard to say what is the issue there. But it isnt a bug on our side.
