### ISSUE TITLE
Restore gsm code calling from favorites

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Dialer#468]
"I have stored some gsm codes for call forwarding in my contacts for easily switching on and off status, e.g. "##002#", and flagged them as favorites.

When I now start a call via the contacts tab in the dialer everything works as expected and a call to "##002#" is executed.

However when I try a call via the favorites tab, the call is not properly executed as only "002" is dialed.

This wrong behavior seems to have been introduced via a recent update because it had worked previously."

**Comment by MohitMaliFtechiz** [comment]
hi @tibbi ,

I have tried to replicate this issue on android 9 , android 11 but it was working fine . I am attaching video of working , let me know if i am missing anything.


https://user-images.githubusercontent.com/34593983/202433658-9bb85b01-0bc5-41a4-a69a-11ff00ac922b.mp4

**Comment by tibbi** [comment]
asked the reporter if it still happens to him, lets wait for the response.

**Comment by liyamahendra** [comment]
@tibbi did we hear back on this?

**Comment by tibbi** [comment]
nop

**Comment by ankagu** [comment]
https://github.com/SimpleMobileTools/Simple-Dialer/assets/136325826/b8f9ff06-eb63-405a-a51f-d97ce1143e73


https://github.com/SimpleMobileTools/Simple-Dialer/assets/136325826/56c6951c-bdcf-4dd9-afc9-3450cef85035

Hi,

I´m having this issue also.

My phone model is Motorola Moto G8 Power running Android 11.

I made 2 videos, one with the dialer where you can see the issue and another through the contacts app where it works as i should.

I´m running some "customizations" like Nova Launcher and other stuff, I can add more info if you want.

I installed the software through F-Droid: Dialer version 5.17.8 and Contacts version 6.22.3 Pro

Regards,

Anders
