### ISSUE TITLE
Missing space in French missed call notification

### ISSUE THREAD

**Issue by Junkyard-Dog-0101** [SimpleMobileTools/Simple-Dialer#476]
![Screenshot_2022-11-10-16-37-34-69_765f8dabff0c1b40e2676405b965e035](https://user-images.githubusercontent.com/3962335/201139125-fc35c050-4efe-4a5d-8925-ea85b867a71c.jpg)

Between number of missed call and the text

**Comment by tibbi** [comment]
that is handled by the system, not us
