### ISSUE TITLE
Call history: not showing/saving call log

### ISSUE THREAD

**Issue by rtyujik** [SimpleMobileTools/Simple-Dialer#48]
Not showing or saving call log in call history saying "No previous calls have been found".

Android 8.1 / No Gapps / No default system apps.

**Comment by tibbi** [comment]
and do you have any calls? Do they show up well in other apps?

**Comment by rtyujik** [comment]
> and do you have any calls? Do they show up well in other apps?

I had one, but it also doesn't show calls I made.

**Comment by tibbi** [comment]
well you seem to have broken your device then, not much I can do about it
