### ISSUE TITLE
HTTP request just before receiving the call

### ISSUE THREAD

**Issue by abdul-jabbar-ms** [SimpleMobileTools/Simple-Dialer#485]
Hi, it is not an issue actually but a humble request. On 3g networks, the data connection goes away when it starts ringing in your app. I need to send an http request just before ringing. Is it possible? If yes, can you please guide me at which place/file I can add this? 

I am a beginner and will be very thankful for any help.

**Comment by tibbi** [comment]
no, our apps have no internet access
