### ISSUE TITLE
Contacts list: cannot launch contacts app

### ISSUE THREAD

**Issue by rtyujik** [SimpleMobileTools/Simple-Dialer#49]
In contacts list plus button to add new contact says "No valid app found" - maybe on fail it should try to launch com.simplemobiletools.contacts/pro instead?

Also "Create new" button doesn't react.

NOTE: Same problem for "Create new contact" and plus button in "Select contact" window when adding from Dialpad

Android 8.1 / No Gapps / No default system apps.

**Comment by rtyujik** [comment]
Contacts added within Simple Contacts app is also not visible in dialer.

**Comment by rtyujik** [comment]
Any way I could record app log for you?

**Comment by tibbi** [comment]
Does it work well in other apps? You seem to have broken your device somehow with deleting all those system things.

**Comment by tibbi** [comment]
actuall ye,  according to #48 you have indeed gone too far with deleting some system functionality, there isnt anything I can do on my side
