### ISSUE TITLE
Two Icons/buttons merged

### ISSUE THREAD

**Issue by Moxville** [SimpleMobileTools/Simple-Dialer#494]
Honor 9 STF-L09
EMUI version 9.1.0
Android 9
Simple Dialer 5.16.0

I noticed two buttons merged. I request for a fix. Thanks for the nice app :)
![Screenshot_20221203_212710_com simplemobiletools dialer](https://user-images.githubusercontent.com/31923265/205451142-4fb4a95b-21d8-4604-ad0d-7e8a07f78120.jpg)

**Comment by tibbi** [comment]
should be fixed in the next app version already
