### ISSUE TITLE
Input number is not centered, but it is in the in-call UI

### ISSUE THREAD

**Issue by mijorus** [SimpleMobileTools/Simple-Dialer#498]

**Comment by tibbi** [comment]
can you send a screenshot of what you mean?

**Comment by mijorus** [comment]
![image](https://user-images.githubusercontent.com/39067225/206421363-72aa22e4-be4a-424b-9c23-6b3956ffd0c2.png)
 
this is more a feature request than a bug, I think that this number should be centered vertically relatively to the screen

**Comment by mijorus** [comment]
![206421363-72aa22e4-be4a-424b-9c23-6b3956ffd0c2](https://user-images.githubusercontent.com/39067225/206526996-1e53e50c-4c7b-4dee-bc02-2e77727624e6.png)

basically I think that the number should be aligned like this.

**Comment by tibbi** [comment]
you were talking about vertical centering previously, not horiozntal..
