### ISSUE TITLE
Add search icon in favorite and recent views

### ISSUE THREAD

**Issue by siccovansas** [SimpleMobileTools/Simple-Dialer#50]
Thanks for this great app!

It would be nice to have the search icon on all views. Currently it is only available in the 'contact list' view, but it is nice to also quickly access the search function in the 'favorite' and 'recent calls' views.

For example. Samsung's dialer does this in all of its views.
![signal-attachment-2020-06-04-170651_003](https://user-images.githubusercontent.com/696839/83774989-b7efdc80-a686-11ea-8feb-ea5b87595b0b.jpeg)
![signal-attachment-2020-06-04-171029](https://user-images.githubusercontent.com/696839/83774991-b8887300-a686-11ea-8803-de2c9a6abf99.jpeg)
![signal-attachment-2020-06-04-170651_001](https://user-images.githubusercontent.com/696839/83774994-b9210980-a686-11ea-8c43-1dc901597fd7.jpeg)

When you click on the search icon it 'overlays' a search view like this:
![signal-attachment-2020-06-04-171557](https://user-images.githubusercontent.com/696839/83775628-76abfc80-a687-11ea-973f-4440a38c8c9f.jpeg)

**Comment by tibbi** [comment]
it has been added already
