### ISSUE TITLE
Option to call a contact directly upon pressing it

### ISSUE THREAD

**Issue by Moxville** [SimpleMobileTools/Simple-Dialer#501]
Simple Dialer 5.16.0 (installed)

In "contacts" tab, when I press a contact every time it takes me to below mentioned screen. Only upon pressing the phone icon the contact person is dialed.
An option (under Settings) which allows me to directly dial the contact upon pressing it would be useful. It would help my mother a lot to avoid confusion (My mother asked me why the contact is not dialed upon pressing the contact name)
![Screenshot_20221210-101113](https://user-images.githubusercontent.com/31923265/206842557-d64ab1b5-f1f4-4689-ae4f-3177d9dcc524.png)

**Comment by tibbi** [comment]
you can already change what happens on contact clicking in the app settings. Long pressing is reserved for selection in most apps
