### ISSUE TITLE
Add a crowdsourced phone number database

### ISSUE THREAD

**Issue by popogomo** [SimpleMobileTools/Simple-Dialer#506]
There is an app on F-Droid called Yet Another Call Blocker. 

It uses an offline crowdsourced phone number database that automatically identifies spam calls / telemarketers, etc. So if someone calls, the app advises if its a suspicious caller based on the database entries. 

Would be great if you consider implementing this into Simple Dialer so that it will recognize these suspicious calls. 

The Dialer could download the database once per week or so to keep it up to date, just like Yet Another Call Blocker does.

**Comment by tibbi** [comment]
that isnt on the roadmap

**Comment by jaredsburrows** [comment]
@tibbi What do you need to make this on the roadmap?

**Comment by tibbi** [comment]
I dont like increasing app sizes with such numbers that are relevant only to a tiny amount of users.
