### ISSUE TITLE
[Theme] Odd material design

### ISSUE THREAD

**Issue by biopsin** [SimpleMobileTools/Simple-Dialer#513]
Heya, 
updated today to v.5.17.0 and there seems to be some weirdness with the theme.
When the application loads top banner has no color and is missing appname
![Screenshot_20221231-153446_Trebuchet](https://user-images.githubusercontent.com/60029989/210140515-94bb9561-b057-402d-bdf6-3fd9abc8f309.png)

Then scroll down some and the color appear
![Screenshot_20221231-153453_Trebuchet](https://user-images.githubusercontent.com/60029989/210140539-0763d517-1b5b-45f8-843b-87df0dc44e27.png)

Same thing with dialpad
![Screenshot_20221231-153503_Trebuchet](https://user-images.githubusercontent.com/60029989/210140564-0d815022-2675-4ef2-a4a5-dd572ebb3002.png)

Then scroll some
![Screenshot_20221231-153509_Trebuchet](https://user-images.githubusercontent.com/60029989/210140573-46ddbc12-a164-4c2d-8ee5-c5e4c96bd287.png)

I guess I expect a constant blue header with appname like in previous versions.
(Lineageos-18.1 / xperia 1ii)

**Comment by tibbi** [comment]
it works as expected now, will see if it needs some updates

**Comment by tibbi** [comment]
I actually want to redesign the top bar with having bigger Search, but didnt manage doing it yet

**Comment by biopsin** [comment]
I see, are you thinking of replasing the magnifyglass icon with a textfield?

**Comment by tibbi** [comment]
ye, would like such a toolbar

![search](https://user-images.githubusercontent.com/528931/210168465-83a453a4-fc60-43e6-b2b3-bd008b49f811.jpg)

**Comment by biopsin** [comment]
Just tested it on the updated Messanger and it soo functional and looks beautiful, Yes please!

**Comment by tibbi** [comment]
thanks :) I want to improve a few more things around the search and maybe add an animated transition between search and arrow icon, but ye, looks good so far.
