### ISSUE TITLE
Version 5.17.1 does not show the dialpad

### ISSUE THREAD

**Issue by foolioo** [SimpleMobileTools/Simple-Dialer#521]
After updating to version 5.17.1 (Android 8), the app shows only the search bar, contacts, call history but not the dialpad. Which does not let one perform a call to a number that is not in the contact list.

Before the update, everything was working well.

Here is a snapshot where the dialpad button on the bottom right is missing (contacts have been censored from the screenshot without the dialpad button itself).
![image](https://user-images.githubusercontent.com/28758375/211279173-86a42501-792f-407b-ae54-8c886ca4bbd9.png)

**Comment by tibbi** [comment]
send a screenshot of what you mean please

**Comment by sphh** [comment]
I can confirm that the icon to call up the dialpad is missing after upgrading to 5.17.1 on my phone.

**Comment by sphh** [comment]
Yes, my Android is 8.1.0.
