### ISSUE TITLE
Contacts missing in 5.17.1

### ISSUE THREAD

**Issue by glocalglocal** [SimpleMobileTools/Simple-Dialer#523]
Similar to #521, only here the contacts are missing too. The only way to get them back is to kill the app and restart. 

![image](https://user-images.githubusercontent.com/16408198/212174606-3502c338-de1c-445b-a575-fb5fe57eb103.png)

Similar to https://github.com/SimpleMobileTools/Simple-SMS-Messenger/issues/549

Android 7, v5.17.1

**Comment by tibbi** [comment]
will be fixed in 6.22.1 released soon, just update whenever it becomes available
