### ISSUE TITLE
How to remove the default SIM card for a contact?

### ISSUE THREAD

**Issue by mijorus** [SimpleMobileTools/Simple-Dialer#527]
I have wrongly selected "use always SIM 1" for a contact and I can't find a way to reset this option

**Comment by tibbi** [comment]
you can long press the wanted item at recents and use the top Menu -> Remove default

**Comment by mijorus** [comment]
@tibbi 

This option is not showing for me.
Tested on 5.17.3

![Screenshot_20230119-123555~2.png](https://user-images.githubusercontent.com/39067225/213432572-6e7f6bcf-e79c-4c4e-bf35-b5c05abf5b01.png)

**Comment by tibbi** [comment]
what screen is that? looks weird

**Comment by mijorus** [comment]
it is the recents screen

**Comment by tibbi** [comment]
and you have a default SIM set for that number? Thats when it should appear, will keep an eye on it.

**Comment by mijorus** [comment]
https://user-images.githubusercontent.com/39067225/213437496-f1f80ede-92e4-483f-99f8-107d38858bd0.mp4

**Comment by mijorus** [comment]
> can you reproduce it with any number?

Any Number
