### ISSUE TITLE
[Android 11] Annoying toast message when call ends.

### ISSUE THREAD

**Issue by CortexReaver** [SimpleMobileTools/Simple-Dialer#528]
There is a very annoying message with total call time, which is showing on the screen every time when call ends and there is no way to disable it (I've tried several toast blocking apps and none of them is working). Can you disable it completely or at least make an option for not showing it?

**Comment by tibbi** [comment]
can you make a screenshot of what you mean?

**Comment by CortexReaver** [comment]
![Screenshot_20230120-161956](https://user-images.githubusercontent.com/34350690/213705415-d7721c40-07ce-4789-99ab-d3fcf1e815d1.png)

**Comment by tibbi** [comment]
that definitely doesnt come from us
