### ISSUE TITLE
call issue in a two calls scenario

### ISSUE THREAD

**Issue by yonatan-tesfay** [SimpleMobileTools/Simple-Dialer#529]
The problem arises when I am in active call and I add another call, if the second call declines the app returns to the first call with the **status text as dialing instead of showing the call duration, and puts the call onhold state but the hold button is not onhold.** I assumed it is putting the call onhold since the call resumed when I clicked the onhold button.

**Comment by tibbi** [comment]
that is way too advanced case for our app
