### ISSUE TITLE
the search bar introduced in v5.17.1 doesnt look good

### ISSUE THREAD

**Issue by yashpalgoyal1304** [SimpleMobileTools/Simple-Dialer#537]
hi!

thanks a lot for the material u update in v5.17.0, it looks very nice.

but the search bar's contrasting color introduced in v5.17.1 pulls toooo much of attention. it would have looked way better if its colors were in harmony with background

**Comment by tibbi** [comment]
we dont really plan removing it now

**Comment by yashpalgoyal1304** [comment]
i am not saying to remove it, but to theme it better
