### ISSUE TITLE
[FR/Bug]: Simple Contacts' filter settings should be taken into account when displaying contacts

### ISSUE THREAD

**Issue by just-Nob** [SimpleMobileTools/Simple-Dialer#54]
# Environment:
### Simple Dialer:
* v.5.3.0, taken from F-Droid repo
### OS:
* LineageOS 17.1
### System Modding:
* root
* Framework: Magisk, EdXposed
* Security: AFWall+, Xprivacy Lua
* Misc: GravityBox, Exposed Edge, Easer, some others
### Hardware:
* BQ Aquaris X Pro

# Description:
_Simple Dialer_ has it's own contacts view (left column). This view seems to grab all contacts available to display them, independent of _Simple Contacts'_ current filter settings.
_Simple Contacts'_ filter settings should be taken into account by _Simple Dialer_ as well. An alternative would be a sperate filter to be set in _Simple Dialer_, but I'ld prefer one filter for both apps.

# How to reproduce / enamples:
### Scenario A:
1. Using _Simple Contracts_, add at least one contact and store it/them into the "Phone storage" section ("not visible by other apps").
2. Set _Simple Contracts'_ filter not to display contacts stored into the "Phone storage" section. The contact(s) isn't (aren't) visible in the _Simple Contacts_ app anymore.
3. Switch to the _Simple Dialer_ app.
4. Switch to _Simple Dialer's_ contact overview (left column).
5. The contact(s) you added like defined in _item "1."_ is visible in that view, although these contacts are filtered (in _Simple Contacts'_ filter settings) not to be shown.

### Scenario B:
1. Perform _items " 1."_ & _"2."_ of _Scenario A_, if not already done.
2. Open _Simple Contracts'_ dialpad.
3. In the upper part of the screen above the dialpad itself, a list of available contacts is shown. That list contains also the contact(s) stored into the "Phone storage" section, although these contacts are filtered (in _Simple Contacts'_ filter settings) not to be shown.

**Comment by tibbi** [comment]
Simple Dialer will receive a standalone Filter menu item, it shouldnt be connected to Simple Contacts
