### ISSUE TITLE
Unknown number calls are not registered

### ISSUE THREAD

**Issue by Gravity2106** [SimpleMobileTools/Simple-Dialer#541]
Incomings calls from a hidden number are not recorded

**Comment by tibbi** [comment]
what do you mean not recorded? They arent in the call log tab?

**Comment by tibbi** [comment]
ok, try this one please, the app should be called Dialer_debug. Check if it handles private entries properly. You might have to allow installing apps from unknown sources in the security settings of your device. After downloading the file remove the .zip extension by simple renaming, do not try decompressing it. Github doesnt allow uploading .apk files so I had to append .zip to it. Thanks

[dialer-core-debug.apk.zip](https://github.com/SimpleMobileTools/Simple-Dialer/files/11816213/dialer-core-debug.apk.zip)

**Comment by tibbi** [comment]
@Gravity2106 how has i worked?

**Comment by Genis-Sage** [comment]
@tibbi 
the issue is still in the last release 2.18.1

but I tried the debug apk - there anonymous calls are shown (it identifies itself as 2.18.0)

**Comment by inson1** [comment]
@Genis-Sage SMT apps were sold to ad company. Fork is here https://github.com/FossifyOrg
