### ISSUE TITLE
Feature: Please add addressbook filter

### ISSUE THREAD

**Issue by SIRSteiner** [SimpleMobileTools/Simple-Dialer#545]
Please add filter like in contacts app, maybe also groups
Thank you

Btw: Would it make sense to unite phone and contacts app to one app?

**Comment by tibbi** [comment]
it is on the roadmap. Contacts and Dialer used to be 1 app, but had to be split due to Android restrictions

**Comment by SIRSteiner** [comment]
Thank you. And what about adding filter?

**Comment by SIRSteiner** [comment]
Again: And what about adding filter?

**Comment by Aga-C** [comment]
It will be released in the next app version: https://github.com/SimpleMobileTools/Simple-Dialer/pull/558.
