### ISSUE TITLE
Compatibility with older Android versions

### ISSUE THREAD

**Issue by fturco** [SimpleMobileTools/Simple-Dialer#55]
I successfully installed Simple Contacts on my smartphone via F-Droid, but I can't do the same with Simple Dialer because the former is compatible with Android 5.0 or newer while the latter is only compatible with Android 6.0 or newer.

I still have an Android 5.1 smartphone.

Is there any possibility of changing the Simple Dialer app in order to make it compatible with older Android versions?

**Comment by tibbi** [comment]
no, sadly the minimal OS 6 is there for technical reasons, not for lazyness
