### ISSUE TITLE
"Call back"  button on missing call does not work

### ISSUE THREAD

**Issue by HristiyanBostandzhiev** [SimpleMobileTools/Simple-Dialer#551]
When I have missing call, this appears 
![Без име](https://user-images.githubusercontent.com/127140061/223208134-4857e6d6-0bc5-42c6-bfef-0ba74724f7ca.png)
And when I click on "Call back" the window closes and nothing happens.

Device : Huawei Y5p
![334935298_587242103450091_4763626976747001168_n](https://user-images.githubusercontent.com/127140061/223208380-563a9f3d-8538-450e-8223-b8d3c41781b9.jpg)

**Comment by gtrplair** [comment]
Hi, I am a student at University of Paris 8 and I would like to contribute to this repository as an end-of-year project. Can I be assigned this issue?

**Comment by tibbi** [comment]
@gtrplair sure

**Comment by tibbi** [comment]
it works to all devs and myself too and it is handled by the system, so Ill close it as not an issue on our side
