### ISSUE TITLE
bug in Kiosk mode when incoming call

### ISSUE THREAD

**Issue by francoisnicolas** [SimpleMobileTools/Simple-Dialer#556]
When the smartphone is in Kiosk mode and there is an incomming call, the window showing that there is an incomming call doesn't appear. (We ear the ring of the call). The window is surely hidden by the actual app that is running.
The app has been added in whitelist of app that can be launched in Kiosk mode

**Comment by tibbi** [comment]
What is kiosk mode? Do other downloaded Phone apps work well?

**Comment by francoisnicolas** [comment]
https://developer.android.com/work/dpc/dedicated-devices
There is only one app that run on the device, and user can't install other app.
(you can authorize some apps, and add in whitelist in the kiosk app)

**Comment by tibbi** [comment]
Do phone calls work well with casual device usage, without kiosk mode?

**Comment by francoisnicolas** [comment]
Your app works well without kiosk mode.

**Comment by francoisnicolas** [comment]
Don't worry about this issue, I just realized that even samsung's phone app can't be launched to dial in Kiosk mode. Yesterday, I only managed to receive calls.
As the Kiosk mode is used by very few people, especially to receive and make calls, do not spend time on this problem
