### ISSUE TITLE
Not display call log history

### ISSUE THREAD

**Issue by ghost7744** [SimpleMobileTools/Simple-Dialer#559]
Hello,

I decided to disable various services and applications that I not use. And stopped working the call history log. It's empty, everything has been removed. Which service or application is responsible for display the call history log?

**Comment by tibbi** [comment]
Hard to say, it could be device specific. You should know what you disabled.

**Comment by ghost7744** [comment]
Awesome help  😂 😂 😂

**Comment by tibbi** [comment]
well, the issue isnt related to our app

**Comment by ghost7744** [comment]
OK  😂 😂 😂
