### ISSUE TITLE
Unable to view private contacts

### ISSUE THREAD

**Issue by W1zardK1ng** [SimpleMobileTools/Simple-Dialer#562]
When using dialer app instted using the apk file downloaded github, unable to view private contacts even after enabling the option in Simple contacts app.
When installed the dialer app from F-droid everything works as expected.

**Comment by tibbi** [comment]
what app versions are you using?

**Comment by W1zardK1ng** [comment]
I checked the version just now, was having issue on the on the 5.17.4.
reinstalled the github version of 5.17.3, now everything works as expected.

**Comment by biopsin** [comment]
After update of contacts to 6.22.2, contaktlist in dialer 5.17.4 are unviewable

**Comment by tibbi** [comment]
will take a look at it

**Comment by biopsin** [comment]
@tibbi managed to reproduce?Ive tried reinstalling contacts, reimporting contacts but they just dont show in the dialer on loglist is visible.

**Comment by tibbi** [comment]
ye, will be fixed in the new app version
