### ISSUE TITLE
Call cutting off after 29min 32sec

### ISSUE THREAD

**Issue by MeinChef** [SimpleMobileTools/Simple-Dialer#567]
Hello SimpleMobileTools!
I've experienced this weird behaviour while recieving a call from someone (incoming call), after exactly 29min and 32 sec the call cut off. Until now I've not had a call longer than this timespan with someone else. To rule out a problem at their end, I've received a call from them using another dialer and was able to get over the 29.32min mark.
![Screenshot_20230328-102512_com.simplemobiletools.dialer](https://user-images.githubusercontent.com/126389277/228180001-f850392e-0cd9-4f13-b0b5-aa02c4ab351f.jpg)
I've loved your apps so far! If you do need anything else I can provide you, I'll gladly do so :)

**Comment by tibbi** [comment]
that is a really weird issue, does it happen with every contact or just a specific one?

**Comment by MeinChef** [comment]
I'm sorry, I haven't tested this yet. 
Will update you if it repeats.

**Comment by TheCodingArcher** [comment]
Happening to me too at 15:40 minutes on any call.

**Comment by MeinChef** [comment]
After a reboot the problem did not persist.
