### ISSUE TITLE
Cannot delete individual entries in call log

### ISSUE THREAD

**Issue by popogomo** [SimpleMobileTools/Simple-Dialer#568]
Dialer version: 5.17.5
Android: 13

Thanks for such an amazing app!

I am experiencing the following issue:

1. Open Dialer and tap to Call History
2. Tap and hold one or a few entries to select them
3. Now tap to Delete button in the top to delete these selected entries
4. The entries will disappear from Call History
5. Now tap to Contacts tab or just close and re-open the Dialer and navigate to Call History tab: the deleted entries will re-appear again as if they never been deleted. So the app doesn't delete one or a few selected entries.

However, if we delete ALL entries (by tapping to bin button in the top, without selecting any individual entries) then it will properly delete ALL entries. 

So the issue is only when deleting one or multiple selected entries.

**Comment by tibbi** [comment]
try disabling "Group subsequent calls with the same number at the call log" setting, isnt that causing the glitch?

**Comment by Aga-C** [comment]
Have you been closing the app completely (kill it in the background)?
