### ISSUE TITLE
Fix number pressing behaviour during calls

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Dialer#573]

**Comment by Elciis** [comment]
Hello !  I contact you to share a problem that I have.  During a phone call the numeric keypad seems to be inactive.  when I call my answering machine and wish to delete a message, the corresponding key performs no action.  I have the same problem when I call a call center and have to navigate with the dial pad to get the desired service.  Thanks in advance for the response

**Comment by tibbi** [comment]
Hi, was it working previously?

**Comment by AtomMobile** [comment]
We are also having his issue.
It appears that after the most recent update, the keypad no longer works.

The app was working previously.

App version: 5.17.5
Device OS: 11

**Comment by Elciis** [comment]
Thank you for the feedback.  yes the keyboard worked before.

**Comment by ismailnurudeen** [comment]
Okay, I'm currently investigating this issue and would be resolved soon.

**Comment by istvan-andrasi** [comment]
Pressing numbers during calls does not work for me either.
Samsung Galaxy S22

**Comment by ismailnurudeen** [comment]
I have a theory about this issue and I will like to confirm it before proceeding with a fix.

If you go to Settings on the app and check `Enable beeps on dialpad button clicks`, the number input during calls starts working and if you uncheck it, the issue returns.

Please try this and let me know if that's what actually happens.

**Comment by Elciis** [comment]
yes, the theory is correct.  if I reactivate the keypad beep, the keypad works again during calls.  😁

**Comment by istvan-andrasi** [comment]
Yes, enabling beep makes it work again for me as well.

**Comment by ismailnurudeen** [comment]
Thanks guys, a fix is on the way 🛠️

**Comment by AtomMobile** [comment]
FYI, in my case, I enabled the beeps, and the issue was fixed. However, when I un-checked dial pad beeps, the issue was still fixed… I could still use the dialpad.
