### ISSUE TITLE
Option to delete all call log entries

### ISSUE THREAD

**Issue by x-jokay** [SimpleMobileTools/Simple-Dialer#58]
An option to delete all call log entries would be great.

**Comment by tibbi** [comment]
well just select an item by long pressing it, then press the "1/xxx" button at the top left corner to delete all shown entries. It will delete the last 100 entries which are currently fetched. I dont plan adding a new button for deleting all of them.

**Comment by x-jokay** [comment]
thx, this works perfectly 👍
