### ISSUE TITLE
Inconsistent history format 

### ISSUE THREAD

**Issue by glocalglocal** [SimpleMobileTools/Simple-Dialer#583]
Call history displays known numbers in at least three different ways: 
1. `+4471234567`: That's when I select one of of my stored numbers to call (I always store numbers with their international prefix +xx) 
2. `071234567`: When I receive a call from the known contact above or when I call back using this incoming call entry. 
3. `+4471234567 - Mobile`: As in (1) above but this time I have favorited the mobile number of the contact. 

This is all very confusing and disrupts the grouping in history. All incoming and outgoing calls should be displayed in format 3 with or without the internation prefix depending on how the user has stored the number. That would be provide consistency, undisrupted grouping of history entries and useful details.

**Comment by tibbi** [comment]
we show whatever is stored in the system, we arent modifying it in any way.
