### ISSUE TITLE
Can not read sim number from dual sim slots from sim card manager 
In one slot it read and in the other is just shows +country code

### ISSUE THREAD

**Issue by salman1001** [SimpleMobileTools/Simple-Dialer#584]

**Comment by tibbi** [comment]
not sure what you mean or where, can you send some screenshots?

**Comment by tibbi** [comment]
so you have some developer issue, not a user one?

**Comment by salman1001** [comment]
Correct.

**Comment by salman1001** [comment]
> so you have some developer issue, not a user one?

![IMG_20230414_091039.jpg](https://user-images.githubusercontent.com/55211374/231935952-35a0cba3-1952-4015-9f70-9b189183e8b3.jpg)

Look at this it read just one sim slot and could not read the other one

**Comment by tibbi** [comment]
we dont give out dev support
