### ISSUE TITLE
Since version 5.17.5 Simple Dialer can't access phone book

### ISSUE THREAD

**Issue by pezcurrel** [SimpleMobileTools/Simple-Dialer#585]
Since version 5.17.5 Simple Dialer doesn't show the phone books. I'm running 5.17.6 on Android 9 on a Samsung Galaxy SM-J530F. Simple Contacts 6.22.2 Pro has no problem accessing the phone books, it gives me the possibility to select phone books from WhatsApp, Signal, vnd.sec.contact.phone, primary.sim.account_name, "phone memory"; Simple Dialer, instead, just lets me select "phone memory" (which is empty).

**Comment by tibbi** [comment]
update to 5.17.7

**Comment by pezcurrel** [comment]
> update to 5.17.7

Did it, same bug (i uninstalled 5.17.3 before, deleting its cache and data too; now i'm stuck with 5.17.7 since on f-droid 5.17.3 is no longer available, and the apk doesn't install)
