### ISSUE TITLE
5.17.5 does not show Favorite contacts

### ISSUE THREAD

**Issue by cehteh** [SimpleMobileTools/Simple-Dialer#587]
I am using the simplemobiletools address book app as well. Addresses are stored on device, no server. All addresses show up in the dialer, but when i change to show only favotite/starred contacts the pane is empty.

**Comment by Aga-C** [comment]
Are you storing contacts in Simple Contacts as private contacts?

**Comment by Aga-C** [comment]
>ah thats new? it worked before, figured it out now, thanks

It's nothing new, I just wanted to know more details about the bug you're raising. My question was, whether your contacts, that you have in Simple Contacts, are stored in `Phone storage (not visible by other apps)`?

**Comment by cehteh** [comment]
On 2023-04-14 11:29, Agnieszka C wrote:

>>ah thats new? it worked before, figured it out now, thanks  
>
>It's nothing new, I just wanted to know more details about the bug
>you're raising. My question was, whether your contacts, that you have
>in Simple Contacts, are stored in `Phone storage (not visible by other
>apps)`?

yes they where, i changed that to phone storage (visible to other
apps). I am just wondering, i think the favorites where shown before,
or maybe i am misremmebering and used the contacts to dial favorites
not the dialer.

**Comment by Aga-C** [comment]
I've checked on 5.17.7, and I can confirm that favorites doesn't work for private contacts. It was working a few versions back for sure.

**Comment by cehteh** [comment]
On 2023-04-14 12:08, Agnieszka C wrote:

>I've checked on 5.17.7, and I can confirm that favorites doesn't work
>for private contacts. It was working a few versions back for sure.

notice: this kindof strange but not so important as I can workaround
this. The other bugreport i send earlier that the dialer crashes when
bringing up the dialpad is really annoying.
