### ISSUE TITLE
Call history does not show contact photos

### ISSUE THREAD

**Issue by smasty** [SimpleMobileTools/Simple-Dialer#59]
While the Contacts/Favorites tabs show contact photos just fine (see screenshot 1), the Call History does not show contact photos, instead only displaying the default "first letter with colored background" (see screenshot 2)

Simple Dialer version 5.3.0 from FDroid, "vanilla" Android 10 on a Pixel 3a

Screenshot 1: _Contacts tab shows contact photos properly_
![image](https://user-images.githubusercontent.com/218524/84567075-8ce84580-ad76-11ea-92c2-09115f2ef504.png)

Screenshot 2: _Call History tab does not show contact photos at all_
![image](https://user-images.githubusercontent.com/218524/84567085-9d98bb80-ad76-11ea-838a-9cd1f95037c6.png)

**Comment by tibbi** [comment]
dont you have those contacts stored under "Phone storage (not visible in other apps)" at Simple Contacts?

**Comment by smasty** [comment]
No, all my contacts are synced from DAVx5. I should also mention it's not that some contacts don't have a photo in call history, it's all of them.

**Comment by msva** [comment]
I've similar issue even on first launch: same contacts do have photos in the history, but the very last calls from the same contacts - does not...
![](https://i.imgur.com/yrCJ9yW.png)

**Comment by gsantner** [comment]
For me, no pictures show up at all on the  recent history tab.  
Pictures however do show up at dialer/contactlist, dialer/favourites and in the other simplemobiletools/contacts app.

**Comment by igor-cali** [comment]
> No, all my contacts are synced from DAVx5. I should also mention it's not that some contacts don't have a photo in call history, it's all of them.

Same behaviour to me, my contacts are synced from DAVx5.

**Comment by igor-cali** [comment]
> > No, all my contacts are synced from DAVx5. I should also mention it's not that some contacts don't have a photo in call history, it's all of them.
> 
> Same behaviour to me, my contacts are synced from DAVx5.

@tibbi I ran some test trying to review the code on Android 10. As far as I see, the contact images are correctly handled for the contacts and for the call, but then they are not stored/retrieved for the recent calls. To be more precise, I don't know if there is any code here to store the recent call image.

Also, I wonder weather this is handled by Simple Dialer or by the Simple Common library.

In addition, I see some imports in Simple Dialer of `com.bumptech.glide.Glide` (not included in the Gradle dependencies), while Simple Commons sticks to an old Glide release. Not sure if these could impact in this behaviour.

If you can give any hints, I could try to investigate further.

Thanks!

**Comment by Skaalgard** [comment]
Bump?
