### ISSUE TITLE
Simple-Dialer icon disappears from desktop

### ISSUE THREAD

**Issue by sodinoel** [SimpleMobileTools/Simple-Dialer#596]
- unsing Android 10 on a Nokia device, 
- moving Simple-Dialer icon to standard desktop (no app launcher), 
- power down and restarting Nokia device, 
- icon has been vanished.

**Comment by sodinoel** [comment]
OK, how do I solve the problem?
Does switching back to origin icon color help?

**Comment by tibbi** [comment]
sure, or if it wont, reinstall it

**Comment by sodinoel** [comment]
ok, fresh installation, 
not changing color 
(pls disable the option to change the color) 
works for me
