### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by subhashis-barad** [SimpleMobileTools/Simple-Dialer#597]
Adding a call recording would be wonderful,
I was using DIaler,Messages and contacts from ricedroid apps, but I switched to simple dialer, msgs and contacts because of this UI and features. But one thing I miss is a call recording option.

thanks for making this app, this is so so so awesome and cool looking

**Comment by Sureshgorai25** [comment]
> Adding a call recording would be wonderful, I was using DIaler,Messages and contacts from ricedroid apps, but I switched to simple dialer, msgs and contacts because of this UI and features. But one thing I miss is a call recording option.
> 
> thanks for making this app, this is so so so awesome and cool looking

Same for me

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/36.
