### ISSUE TITLE
Simple-Dialer incorrectly displays the company's name

### ISSUE THREAD

**Issue by Hell01World** [SimpleMobileTools/Simple-Dialer#598]
https://user-images.githubusercontent.com/110909985/235613915-a3632eb6-592f-4dbc-b1bc-1ae4d0c6bfb2.mp4

If you create a contact that has more than 2 words, its name will be displayed incorrectly in the Dialer app.

This bug doesn't occur in the Contacts app.

I'm currently using version 5.17.8, which was downloaded from F-Droid.

**Comment by biopsin** [comment]
Relates to #570

**Comment by liyamahendra** [comment]
@tibbi I wasn't able to reproduce on my OnePlus device. Not sure if I misunderstood.

Can we rephrase and say (i) What the current issue is and (ii) What should ideally happen?

On a side note, I observed that Contact changes (Add / Update) don't get reflected until the app is restarted - is that the way the app was developed and suppose to work?

**Comment by tibbi** [comment]
well, there is a video about it too, make sure you save the contact to "Phone storage (not visible by other apps)", that is the key

**Comment by liyamahendra** [comment]
Thank you for the additional info of "Phone Storage". 

I did review the video multiple times. Specifically, I'm looking for below two details:

- What is the exact issue?
- How should the app ideally work?

Also, you saw the side note at the end of my previous comment?

**Comment by liyamahendra** [comment]
@tibbi I added a new contact via native Contacts App. Opened the Dialer, but it didn't show "Google Company, Android Developer" - rather it showed the Contact name with which it was saved. 

Are you able to reproduce the issue yourself?

Let me know your thoughts.


https://github.com/SimpleMobileTools/Simple-Dialer/assets/911879/15cfb72a-0554-4ab0-a2aa-fcf9f1a9ef41

**Comment by tibbi** [comment]
you have to use our Simple Contacts Pro, other apps cannot store contacts into our private space.

**Comment by tibbi** [comment]
the commit improved it, but it still doesnt work well in companies like "A B C D E", it just shows "A E"
