### ISSUE TITLE
possible wrong translation of delete action in "call history" tabs search bar

### ISSUE THREAD

**Issue by da-anda** [SimpleMobileTools/Simple-Dialer#604]
I only have checked this in German, but when you are on the `call history` tab and click on the always visible trash can in the search bar, the confirmation dialog is asking "if you really would like to remove the selected entries" while there are NO selected entires. If you select anything, the search bar changes and the delete button is showing an appropriate dialog.

I assume that the delete icon in the default view will wipe the entire call history, and in that case, at least the German translation is wrong, or the app would have to add a new language label to differentiate between confirming selected items and purging the entire list.

I also would suggest to declutter the UI a bit and move the "purge history" feature to the expandable 3-dots menu.

**Comment by tibbi** [comment]
right, the english version is misleading too
