### ISSUE TITLE
[feature request] move "create new contact" button from search bar to somewhere else

### ISSUE THREAD

**Issue by da-anda** [SimpleMobileTools/Simple-Dialer#605]
in the `contacts` tab of the dialer, there is a "create new contact" button (a simple `+` sign) in the search bar.  My suggestion is to move this button down to the bottom right corner to be in line with the `Simple Contacts` app. Since there currently is the `number pad` button, the number pad button would have to move to the center of the bottom, also just like it is on the `Simple Contacts` app.

**Comment by tibbi** [comment]
they are different apps with different purposes, cannot behave the same
