### ISSUE TITLE
Power button rejects incoming calls?

### ISSUE THREAD

**Issue by xandro0777** [SimpleMobileTools/Simple-Dialer#610]
This happens on my phone although it is 
not enabled in the system settings and not in the app specific settings as far as I can see.

Is that intended? Configurable?
TIA

**Comment by tibbi** [comment]
we definitely havent added anything like that, must be handled by the system

**Comment by xandro0777** [comment]
>we definitely havent added anything like that, must be handled by the system

Was thinking the same, even found the option that would do that but it is disabled
