### ISSUE TITLE
Add vibration when call gets answered

### ISSUE THREAD

**Issue by Ptaski** [SimpleMobileTools/Simple-Dialer#613]
It would be very convenient if phone would vibrate when recipient answers call, as this would avoid issue of wasted time. I guess this could be added as an opt in/out option.

**Comment by v0iden** [comment]
I have a OnePlus phone and use simple dialler, and it vibrates when the call is answered. probably a system thing, it's like this whichever app I'm using.

**Comment by Ptaski** [comment]
So it's a OS thing, well then, I'm closing this issue.

**Comment by v0iden** [comment]
this could still be implemented for those that do not have a phone with this feature. off by default.
