### ISSUE TITLE
bug: menu not respecting theme

### ISSUE THREAD

**Issue by v0iden** [SimpleMobileTools/Simple-Dialer#615]
app is set to follow system theme, but this menu on the front page is always dark for me. oneplus 6t, app version 5.17.18 ![Screenshot_20230523-093231.jpg](https://github.com/SimpleMobileTools/Simple-Dialer/assets/31285047/af5d85c8-87ad-403e-8696-1ff564c4409a)

**Comment by tibbi** [comment]
even if you restart the app?

**Comment by v0iden** [comment]
yes, it's always like this. I've restarted the app many times now while making #616, and toggled the system theme multiple times, but it's always dark when the rest of the app is light.

**Comment by tibbi** [comment]
ah ok, well, menu can change color in Material You theme only, we cannot it dynamically in other cases due to system restrictions. So that is the intended behaviour for now and it likely wont change.
