### ISSUE TITLE
dark mode issues

### ISSUE THREAD

**Issue by v0iden** [SimpleMobileTools/Simple-Dialer#616]
using an OnePlus 6t, app version 5.17.8. I have the app set to follow system theme, but I have several issues with this.

1. have system dark mode enabled for a long time.
2. open simple dialer
3. enable light mode.

expected: the whole app should instantly switch to light mode. 
reality: nothing changes before closing and reopening the app. after that, the main menus, dial pad included, switches to light mode. contacts' details windows, however, do not switch to light mode, and in my experience can go for tens of minutes to hours without changing theme.

I hope this is useful, lmk if any questions

**Comment by v0iden** [comment]
#492 is related. pretty sure I am having the same experience as described in that issue, as well.

**Comment by tibbi** [comment]
some colors cannot be changed dynamically and require an app restart

**Comment by v0iden** [comment]
what about the colors that don't change even after a restart?

**Comment by tibbi** [comment]
just kill the app by swiping away from Recents and restart it
