### ISSUE TITLE
contact info suggestion

### ISSUE THREAD

**Issue by v0iden** [SimpleMobileTools/Simple-Dialer#617]
i wish it was easier to view contact details in the favourites and call history tabs. 

**current situation:**
in the main contacts list, tapping a contact opens the details page. in the favourites and call history tabs, tapping a contact calls them immediately. in order to view contact details here, one must long press on the contact and then press the info button in the toolbar at the top. this is quite cumbersome. 

**proposition:**
in the favourites and call history tabs, tapping the profile picture of a contact opens their details page. 

that way, it's still convenient to call these people quickly, but it's not unnecessarily hard to view details.

**Comment by tibbi** [comment]
I dont really want to split clicking on the picture and the rest, that sounds too confusing. It might improve somehow in the future.
