### ISSUE TITLE
UX Issue: Multiple Call Handling

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/Simple-Dialer#62]
Situation:
On an outbound call to "Wife"
Need to call "Store".

Steps to Repro:
Minimize call screen, launch another instance of Dialer.
Call "Store"
Call connects to "Store", "Wife" call paused

What Happens:
Call screen shows details and controls for "Wife", does not indicate that we are actually connected to the "Store" call, call time is for "Wife" call, does not show "Wife" call as paused

What I expected:
Call screen to show details for current active call for "Store", and indicate that "Wife" call is paused. Call timer would be for the active call, so for "Store"

**Comment by tibbi** [comment]
there is no Pause functionality yet, dont really expect having it anytime soon. Supporting multiple calls at once sounds really messed up.

**Comment by Saijin-Naib** [comment]
Messed up how? Isn't this expected functionality?
