### ISSUE TITLE
Number missing when editing a contact in Dialer

### ISSUE THREAD

**Issue by mibe** [SimpleMobileTools/Simple-Dialer#620]
Hello guys,

I noticed a somewhat strange issue: When editing a contact in Dialer, a number of the contact is mising.

I have a contact with two numbers (mobile and work). When I want to edit this contact, the work number is missing in the edit view. This is only an issue in the Dialer app, when I do the same in the Contacts app it is working flawlessly.

I'm using version 5.17.8 on Android 11.

Here are two screenshots (yellowed out by me):
![Screenshot_20230509-232253](https://github.com/SimpleMobileTools/Simple-Dialer/assets/573529/2fafe3f3-c1c2-4a0f-8c8b-6e79bddad3a9)
![Screenshot_20230509-232314](https://github.com/SimpleMobileTools/Simple-Dialer/assets/573529/6fae5a44-07d1-4b76-8d2b-b28f11097d96)

**Comment by tibbi** [comment]
you cannot edit numbers in Simple Dialer, it opens Simple Contacts. Please report it there with some proper info. I guess you have the contact stored multiple times and it opens the wrong instance.
