### ISSUE TITLE
Ask for a fork of this dialer with only "directly call phone numbers" permission

### ISSUE THREAD

**Issue by serrq** [SimpleMobileTools/Simple-Dialer#624]
There are various apps that offer the ability to disappear from the main launcher, and to reappear make use of the phone dialer.

But I don’t have a SIM card on board and I don’t want to grant special permits.

I need a dialer that doesn’t need to connect to the phone network but just try calling a code like this:  *#*#7777#*#**

Then the app matching that code will be launched.
You can try it with Photok, app on Fdroid.

You could naming the forked app "hidden launcher" or "Fake phone dialer" or what you want.

**Comment by tibbi** [comment]
that isnt on the roadmap
