### ISSUE TITLE
[UI Inconsistency] Contact images are smaller in Call History

### ISSUE THREAD

**Issue by adarsh1001** [SimpleMobileTools/Simple-Dialer#625]
Comparing the Contacts and Favorites screens to the Call History screen, the contact images in Call History are much smaller making the app feel inconsistent overall. Even with Medium text, the text looks quite bloated in comparison to the contact images in Call History screen.

Favorites:
![Screenshot_20230615-234654](https://github.com/SimpleMobileTools/Simple-Dialer/assets/8820038/fcc6e92a-9618-4a69-8622-224d754f15f2)

Call History:
![Screenshot_20230615-234647](https://github.com/SimpleMobileTools/Simple-Dialer/assets/8820038/3788dee2-f03e-44d1-b102-1447a1f461d6)

The difference is noticeable between the two and the inconsistency is apparent when switching screens.

Suggestion: Use the same diameter for images in Call History as other screens.

**Comment by adarsh1001** [comment]
This may be a personal bias but the image diameter of contact images in Favorites and Contacts screens also seem a bit small. Both WhatsApp and Signal, for example, use same diameter of images measuring around 128px in comparison to 118px for this app. It was immediately noticeable for me and was wondering if we should take cues from these apps that use a similar design to better our design as well?

WhatsApp:
![Screenshot_20230616-000739](https://github.com/SimpleMobileTools/Simple-Dialer/assets/8820038/47863114-6282-4c28-aa7c-89937ee28274)

Dialer:
![Screenshot_20230615-234654](https://github.com/SimpleMobileTools/Simple-Dialer/assets/8820038/4aa4de7a-79d2-416a-84a1-6ab19f2a5a12)

**Comment by tibbi** [comment]
well, if different data is shown with a different row count, of course the images can differ
