### ISSUE TITLE
[Feature Request] Possibility of adding feature similar to "iOS contact poster" ?

### ISSUE THREAD

**Issue by Rafee-M** [SimpleMobileTools/Simple-Dialer#627]
I was wondering if a feature similar to iOS's contact poster could be added. 

Could the feature to show fullscreen contact pictures in incoming call screen be added?

Example:
![images(3)_1](https://github.com/SimpleMobileTools/Simple-Dialer/assets/69535896/d9e1190e-0822-4b5a-8af5-3042c5d0c7d2)

**Comment by tibbi** [comment]
not really, it isnt planned
