### ISSUE TITLE
Icons on call activity reset when closing and re-opening app

### ISSUE THREAD

**Issue by chiraag-nataraj** [SimpleMobileTools/Simple-Dialer#63]
Steps to reproduce:
1. Call someone.
2. Mute.
3. Go to home screen.
4. Re-select call from notification.
5. State of mute icon has been reset, indicating that your mic is not muted.

**Comment by tibbi** [comment]
doesnt seem to happen anymore, reopen if it happens after 5.7.+

**Comment by austenadler** [comment]
@tibbi I don't think I have access to reopen, but this is happening to me still on 5.18.0. I can reproduce with:

1. Call
2. Mute
3. Back button (goes back to Dialer contacts/recents/favorites screen)
4. Home (Optional)
5. Open notification
6. Mute button is reset, but mic is still muted

I have never had an issue with the speaker button; only the mute button UI resets.
