### ISSUE TITLE
if not default dailer cannot use

### ISSUE THREAD

**Issue by Oclair** [SimpleMobileTools/Simple-Dialer#634]
I would like to use this app but not depend that it works perfectly.  On my Galaxy S22 it insists the app is the default dailer in order to work.  No Go as the app is a work in progress, so there we are.    Thank you for the open source alternative 😀

**Comment by tibbi** [comment]
thats how the system works, only the default phone app can initiate calls

**Comment by Oclair** [comment]
the response is too general and the user is confused by the response and subsequent closure of the ticket

> thats how the system works, only the default phone app can initiate calls

the system as defined by Android or the apps you have developed bypassing Android OS hardwired to interoperate?


Note: Removing the SimpleMobileTools Dailer restores the ability in SimpleMobileTools Contacts to select 2 separate dialers upon each attempt without designating a default dailer.

Have a great day!
