### ISSUE TITLE
call notification not work

### ISSUE THREAD

**Issue by Jumbo125** [SimpleMobileTools/Simple-Dialer#635]
Hello
I have a problem since my new handy(galaxy s 9)

I don't get any infos when I miss a call.

I enable icon indicator. The call notification is activated, but Gray. I can't change it.

I love your apps and my wife too. 
But if it will not work, I need to change the dialer app, because I don't see, when I miss a call

**Comment by tibbi** [comment]
Missed call notifications arent handled by us. Havent you disabled some system services or the preinstalled Phone app?

**Comment by Jumbo125** [comment]
no. the preinstalled phone app, shows the missing call. but its really confused, when in the preinstalled shows 5 missing calls, but the simple dialer shows no notification or message.
The simple dialer shows only in the call history table the missing call, with the red font-color

**Comment by tibbi** [comment]
as mentioned, missed call notifications are handled by the system, not our app
