### ISSUE TITLE
Phone by google takes over calls before unlocking with fingerprint - password

### ISSUE THREAD

**Issue by ChuckBartowski91** [SimpleMobileTools/Simple-Dialer#642]
Hello, simple dialer is set as default for calls but i cannot answer them if I disable Phone by Google because it will just ring and show nothing even if I unlock it while ringing, just the notification when the call ends.

Disabling fingerprint - password won`t show this behavior.

I've found that Phone by Google is allowed to modify system settings, but not simple dialer, which cannot be allowed to do because is not present, if could be of any help.

The phone is xiaomi 11 lite 5g ne, miui 14.0.6 vf, app version 5.18.0.

All permissions are allowed, into notification there is a voice call_notification_channel which won't let me enable popup notifications.

Thanks.

edit: the app is the f-droid version

**Comment by tibbi** [comment]
do other downloaded Phone apps work well? Is it basically this issue? https://github.com/SimpleMobileTools/Simple-Dialer/issues/574

**Comment by ChuckBartowski91** [comment]
> do other downloaded Phone apps work well? Is it basically this issue? #574

I tried koler and makes the same behaviour. Even simple sms messenger, I need to open the app first.

I've seen the issue and that some fix has been released  but seems to do not work, or maybe there is something I have to do?

**Comment by ChuckBartowski91** [comment]
> If i send you a test app version, can you try it out?

ok, i'll test and report.

**Comment by tibbi** [comment]
Alright, here it is. To install the test version first uninstall your current one and allow installing apps from unknown sources in the security settings of your device. Once you download the file on your device just remove the ".zip" extension. Github doesn't allow sending apk files directly for security reasons. After renaming just run it, it should be straightforward. If you cannot find the item related to installing apps from unknown sources, go into the device Settings -> Apps -> Special app access -> Install unknown apps and select your file manager, or the app you use for launching the sent file, then enable the "Allow from this source" item.

[dialer-core-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Dialer/files/12051958/dialer-core-release.apk.zip)

**Comment by ChuckBartowski91** [comment]
> do other downloaded Phone apps work well? Is it basically this issue? #574

I tried koler and makes the same behaviour. Even simple sms messenger, I need to open the app first.

I've seen the issue and that some fix has been released  but seems to do not work, or maybe there is something I have to do?

> Alright, here it is. To install the test version first uninstall your current one and allow installing apps from unknown sources in the security settings of your device. Once you download the file on your device just remove the ".zip" extension. Github doesn't allow sending apk files directly for security reasons. After renaming just run it, it should be straightforward. If you cannot find the item related to installing apps from unknown sources, go into the device Settings -> Apps -> Special app access -> Install unknown apps and select your file manager, or the app you use for launching the sent file, then enable the "Allow from this source" item.
> 
> [dialer-core-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Dialer/files/12051958/dialer-core-release.apk.zip)

Doesn't work, I gave it all permissions and disabled battery saver and phone by Google, but just rings with no notiifcation shown, if I receive a call before the first unlock after phone reboot.

Since this is a behaviour shown by simple SMS messenger too there could be something wrong with the os or even my phone settings.

**Comment by tibbi** [comment]
What do you mean by SMS Messenger? That works differently, you arent supposed to be able to read the message without unlocking the device. Can you try this one?

[dialer-core-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Dialer/files/12052396/dialer-core-release.apk.zip)

**Comment by tibbi** [comment]
you are testing those things right after restarting your device, without unlocking it at least once?

**Comment by ChuckBartowski91** [comment]
> you are testing those things right after restarting your device, without unlocking it at least once?

Yes. Only phone by Google I'm sure can bypass the first password input.

**Comment by tibbi** [comment]
right, other apps cannot do that..

**Comment by ChuckBartowski91** [comment]
> you are testing those things right after restarting your device, without unlocking it at least once?

Yes. Only phone by Google I'm sure can bypass the first password input.


> right, other apps cannot do that..

Neither alternative phone dialer apps?

**Comment by tibbi** [comment]
I dont know, maybe some system ones. But that is an extreme edge case anyway, I dont want to research it.

**Comment by ChuckBartowski91** [comment]
> I dont know, maybe some system ones. But that is an extreme edge case anyway, I dont want to research it.

Understood. A phone app done by its manufacturer could be ok if doesn't show network usage. But phone by google does (they always say for troubleshooting...) and can bypass the password meaning that they could have full control on the device, this is not so much good to me.

Thanks and sorry for wasting your time.
