### ISSUE TITLE
[Feature request] Option to show call info and not to call right away

### ISSUE THREAD

**Issue by inson1** [SimpleMobileTools/Simple-Dialer#652]
Please, can you do it?

**Comment by tibbi** [comment]
what do you mean, where?

**Comment by inson1** [comment]
In history, I would like to see info about call first and then after click call the number

**Comment by tibbi** [comment]
right, I dont plan changing that behaviour now though

**Comment by inson1** [comment]
@tibbi Oh I meant I want option to call confirmation dialog change to call details.
