### ISSUE TITLE
Allow to revert "Always call with this SIM" choice for contacts

### ISSUE THREAD

**Issue by issueseverywhere** [SimpleMobileTools/Simple-Dialer#66]
Hello,

First, thank you for this app! 

Is it possible to add a way to revert our "Always call with this SIM" choice ?

For example, I called someone today and selected the wrong SIM/operator in the "Always call with..." and know I don't know how to undo this.

I don't know where this option would fit better:
- as a manageable list in general parameters (as the blocked numbers list)
- in the three dots menu of each contacts
- in the edit contacts details, where the automatic SIM for calls options (sim1, sim2,...) would appear as an editable field/menu.

Thank you

**Comment by nikita-moor** [comment]
How to get this feature?

**Comment by tibbi** [comment]
either set a different default sim, or reinstall the app

**Comment by nikita-moor** [comment]
Reinstall did the trick, thank you. However, how to call the `removeCustomSIM` function from GUI?

Let suppose I call a number and I checked "Always use this SIM". After that, I can choose the number in Call History, long press it

![Screenshot_2022-06-29-12-14-04-186_com simplemobiletools dialer](https://user-images.githubusercontent.com/13879891/176375116-f29d0d56-4a51-4d0d-a3f2-ccac97a6cbd2.jpg)

 and get choice: to call the number using SIM1 or SIM2, or open menu (⋮). Nowhere is an item to revert/reset the default SIM.
