### ISSUE TITLE
Getting Purchase And Rate dialogs

### ISSUE THREAD

**Issue by ayounas02** [SimpleMobileTools/Simple-Dialer#662]
How can I disable the random dialogs i get related to Purchase and Rate App?

**Comment by tibbi** [comment]
well, click on a star in the rating dialog. Also for purchasing you should get Simple Thank You

**Comment by ayounas02** [comment]
I dont want to show these random dialogs to end users. 
Will these popups appear in release build?

**Comment by tibbi** [comment]
sure, you arent supposed to republish our apps
