### ISSUE TITLE
block list filter?

### ISSUE THREAD

**Issue by sinjoe** [SimpleMobileTools/Simple-Dialer#663]
im pretty new to this whole foss thing,
but is there support block list filter similar to host/adblock list filter?

similar to this one 
https://gitlab.com/xynngh/YetAnotherCallBlocker
sadly, its gitlab repo? is not being maintain.

Like automatically block known spam number & auto/manual update block list filter.

sorry if its hard to understand

**Comment by tibbi** [comment]
not sure what you mean, you can already block numbers from the app settings

**Comment by Aga-C** [comment]
The same issue was reported here: https://github.com/SimpleMobileTools/Simple-Dialer/issues/506.

**Comment by tibbi** [comment]
our app has no internet access so it cannot be added
