### ISSUE TITLE
Direct call widget

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/Simple-Dialer#664]
Would be nice.

Thanks

**Comment by Aga-C** [comment]
https://github.com/SimpleMobileTools/Simple-Contacts/issues/981#issuecomment-1542156665

**Comment by bb1a2** [comment]
You are right, but Tibor referred the users to the dialer app, so here it is!

**Comment by tibbi** [comment]
nevermind, you can already use shortcuts

**Comment by bb1a2** [comment]
> nevermind, you can already use shortcuts

but shortcuts just open the contact details. This is about **direct** calling. Thanks

**Comment by Aga-C** [comment]
> but shortcuts just open the contact details

No, it's calling immediately.

**Comment by bb1a2** [comment]
> > but shortcuts just open the contact details
> 
> No, it's calling immediately.

I see. I was creating shortcuts from the Contacts app. In Dialer, there is no "create shortcut" option in the call log entries, but after your post, I found the option in the dialpad list of contacts. Thanks.
