### ISSUE TITLE
Support multiple simultaneous T9 languages

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/Simple-Dialer#665]
If you have contacts from various countries:
- some with accented letters (diacritics)
- some in local script/characters
- etc

it would be great if you can set in the options your preferred languages for T9 to match.

Related to #170 

Thanks

**Comment by bb1a2** [comment]
As a quick workaround, you can give the user a list of the 10 numbers (0-9) and allow the user to type in the characters they want for each number.

For example,

1
`'-,`

2
`abcåḁẚćĉc̈ç`

etc

**Comment by tibbi** [comment]
way too advanced for this app...

**Comment by bb1a2** [comment]
I understand. You don't have to adopt this particular solution, but a lot of people are bilingual or multilingual and it would be great if we can search for non-English names. Thanks
