### ISSUE TITLE
Number 1 in T9 should match any punctuation

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/Simple-Dialer#666]
This used to be in my old pre-Android phone. For example `O'connor` should match `6126667`.

Thanks

**Comment by tibbi** [comment]
not really, that doesnt make much sense to me

**Comment by bb1a2** [comment]
This was the actual behavior in Nokia phones. It is not my idea :)

How (currently) do you T9 search for O'connor? I tried `626667` but no match. I can search for `connor` but this is not possible for other names with apostophe in the middle like `Sha'ik`. Thanks
