### ISSUE TITLE
In call log, number type should be an icon/emoji rather than the word

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/Simple-Dialer#669]
Instead of "Tibor - Mobile", something like "Tibor 📱" or "📱Tibor".

This is more dyslexia-friendly and saves space (less truncation of long names).

At least for the common types: mobile (📱), home (🏠), work (🏭), etc.

Thanks.

**Comment by tibbi** [comment]
not really, it shouldnt....

**Comment by bb1a2** [comment]
Your call.
