### ISSUE TITLE
Update name in call log if contact name (in Contacts app) is updated

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/Simple-Dialer#670]
Thanks

**Comment by tibbi** [comment]
that should already work like that

**Comment by bb1a2** [comment]
I tried it.

Steps to reproduce:

- open Dialer, note any contact name.
- open Contacts, edit that contact name.
- open Dialer.
- close Dialer (swipe up in recents) and reopen.

Expected behavior:
- name is updated in Dialer.

Actual behavior:
- old name remains.
