### ISSUE TITLE
Contact/number full history

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/Simple-Dialer#672]
Currently, the history is fragmented if a call to/from other numbers are made in between.

A (6)
B
A (3)
0123456789 (2)
A (2)

When I click the history of A, I want to see the full history (6+3+2).

Thanks

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/380.

**Comment by bb1a2** [comment]
> It's a duplicate of #380.

True. Sorry.
