### ISSUE TITLE
Contact is not shown after creation

### ISSUE THREAD

**Issue by PetrVladimirov** [SimpleMobileTools/Simple-Dialer#678]
How to reproduce:
1. Initiate creation of a new contact
2. Add just a name
3. Press Save
4. Go to Contacts tab
5. Search by the name
6. Nothing will be provided in return. 
7. Stopping/Starting the app doesn't help.
8. The contact was actually saved (it can be viewed via other contact programs).

If saved with a phone number at step #2, after stopping/starting the app the contact is shown

Expected:
1. Newly created contacts are shown immediately after creation
2. Contacts without a phone number are shown if preferred by a user (e.g. via switching the relevant toggle in settings)

Version 5.18 via F-Droid

**Comment by tibbi** [comment]
you are reporting it to Simple Dialer repo, which cannot manage contacts at all. Some other app is invoked at pressing Plus.

**Comment by PetrVladimirov** [comment]
Thanks for the quick turnaround. While contacts are added via another program, the _representation_ and _search_ is done in Dialer (Contacts tab) and it doesn't function correctly. The Dialer doesn't show the newly added contacts in its own interface after searching for this recently added contact, while the other app does see them. It means that the contacts are place, but Dialer (Contacts tab) doesn't show them.

**Comment by PetrVladimirov** [comment]
After restart it starts showing only those contacts that were created with a number in the phone field. 

Contacts with no phone numbers (even after restart):
- Dialer does show old contacts with no phone numbers.
- Dialer does not show newly created contacts with no phone numbers.

**Comment by PetrVladimirov** [comment]
may be because it is called "Contacts"? Some people including me use Dialier's Contacts tab for searching for contacts - many times it is more convenient than opening another app. 

Even if this one intentional, it would help to add a setting option ("show contacts without number") to eliminate confusion.

BTW, what about not showing the contact (even with a phone number) after creation?

**Comment by tibbi** [comment]
you are confusing 2 apps. This issue is created in Dialer, which wont show contacts without numbers. Simple Contacts shows them just fine.
