### ISSUE TITLE
Feature request: Show "Favorites" and "Frequently Called" at the top of dialpad list of contacts

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/Simple-Dialer#681]
Can you please add "the important contacts" (favorites, frequently called) at the top in the dialpad contacts list?

<img src="https://github.com/SimpleMobileTools/Simple-Dialer/raw/master/fastlane/metadata/android/en-US/images/phoneScreenshots/2_en-US.jpeg" width="300">

Thanks a lot

**Comment by tibbi** [comment]
that isnt really on the roadmap
