### ISSUE TITLE
Alert dialog 

### ISSUE THREAD

**Issue by ArunArunkumar** [SimpleMobileTools/Simple-Dialer#682]
I have include your project with my project..(  you are using a fake version of the app
for your own safety download the original one from www.simplemobiletools.com. thanks)
This alert dialog is showing... How to remove or hide this alert dialog.. please kindly help

**Comment by tibbi** [comment]
you arent supposed to republish the app

**Comment by ArunArunkumar** [comment]
Kindly please help how to remove alert dialog. Or hide dialog please
support
