### ISSUE TITLE
Bug: inputting number while using system keyboard

### ISSUE THREAD

**Issue by micwoj92** [SimpleMobileTools/Simple-Dialer#69]
When you are in call, some services use "number commands" in call. Next to keyboard in app, the android keyboard can be used. The problem is that it shows the numbers input but the other number isn't receiving them. 
Version 5.4.0 F-Droid
![Screenshot_20200702_002646_com simplemobiletools dialer_1](https://user-images.githubusercontent.com/45581170/86297291-2fb81500-bbfb-11ea-9d7d-3779d0cdd3de.jpg)

**Comment by tibbi** [comment]
should be working already

**Comment by micwoj92** [comment]
Thanks for fixing.
