### ISSUE TITLE
Call history loading is slow

### ISSUE THREAD

**Issue by Waqar144** [SimpleMobileTools/Simple-Dialer#692]
I have set my default screen to Call History. When I start the app there is roughly a ~2 seconds gap where the call history list is empty and then suddenly loads.

### Expected

Should be instant. Its almost instant on google dialer. In comparison, it was fully instant on 20 year old Nokia dumb phones which had 100x less processing power

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/425.
