### ISSUE TITLE
The contacts match is not right in the call history

### ISSUE THREAD

**Issue by gab12** [SimpleMobileTools/Simple-Dialer#694]
User Case:
1) Create a contact called "Tata" with the number: +33678885678
2) Call your voicemail: in France the number is 888.
3) Go to the call history

Result:
- You'll see that you've called "Tata".
- The call history looks for a number extract and matches it, even if they have nothing to do with each other.

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/683.
