### ISSUE TITLE
Allow for searching contancts with diacritic characters with t9 search

### ISSUE THREAD

**Issue by teklabania** [SimpleMobileTools/Simple-Dialer#707]
Current behavior:
When a contact has a diacritic characters in the name, it's not included in t9 search.

New feature:
Names with diacritic characters should be found with the use of base character (for example: ó -> o, ą -> a). So I could find "Łukasz" as if I typed "Lukasz".

**Comment by tibbi** [comment]
diacritics are ignored

**Comment by teklabania** [comment]
Hi, thanks for looking at the idea. Wouldn't it be a nice feature? There's a bunch of diacritic characters in Slovak as well as far as I know :P I have a few contacts with diacritic characters  both in a name and a surname and it's quite hard to find them with t9.
