### ISSUE TITLE
[Bug] Dialer + Contacts - Search is weird

### ISSUE THREAD

**Issue by inson1** [SimpleMobileTools/Simple-Dialer#711]
![Screenshot_2023-10-18-13-38-23-893_com.simplemobiletools.dialer.jpg](https://github.com/SimpleMobileTools/Simple-Dialer/assets/75314629/ce2366c7-0097-4673-bb10-664896e37a20)

Android 11 MIUI 12.5.7
Dialer 5.18.1

**Comment by tibbi** [comment]
it searched in numbers too, you can see number-letter conversation at the dialpad keys

**Comment by inson1** [comment]
> it searched in numbers too, you can see number-letter conversation at the dialpad keys

Oh Okay. Isnt there any option to block the conversion?

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
