### ISSUE TITLE
Randomize dialpad beep tone

### ISSUE THREAD

**Issue by austenadler** [SimpleMobileTools/Simple-Dialer#713]
It would be nice if dialer could randomize the beep tone so anyone listening can't tell what number you're dailing.

I also noticed that DTMF tones being sent don't make any noise when pressed. If this is because PINs/SSNs are commonly typed, this could allow for a safer way to enable dialpad beeps during calls too.

Proposed PR: #712

**Comment by tibbi** [comment]
thanks, but that isnt really the expected behaviour

**Comment by inson1** [comment]
@tibbi I would like that option
