### ISSUE TITLE
No contacts synchronized

### ISSUE THREAD

**Issue by Aircan** [SimpleMobileTools/Simple-Dialer#714]
The list of contacts is empty. Like so, there are no names displayed, when receiving a call.

Android Version: 14
App version: 5.1.18
OS: GrapheneOS

Contacts do get synced to the phone from a Nextcloud instance using DAVx5. The according contacts Apps still holds the contacts that have been synced.

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/230.
