### ISSUE TITLE
Dialer app new feature

### ISSUE THREAD

**Issue by ticris** [SimpleMobileTools/Simple-Dialer#715]
Hi, everyone,

It is not an issue but a possible new feature.
It would be a nice for the Dialer app to have the phone number displayed in the Call History tab, even for contacts! Could be some situations when someone  might have contacts with more than one phone number saved and it would be great to know which number he/she was called from.

**Comment by tibbi** [comment]
if a contact has more than one number, we show the label like Mobile, Work or whatever is set

**Comment by ticris** [comment]
![Screenshot_20231025_192211_com.simplemobiletools.dialer_1.jpg](https://github.com/SimpleMobileTools/Simple-Dialer/assets/10037010/8a210b7f-b885-4454-9744-1f8082eba938)

Sorry, but I couldn't find the label you mentioned

**Comment by inson1** [comment]
@tibbi I dont see the label either .....
