### ISSUE TITLE
Cannot add a contact to address book

### ISSUE THREAD

**Issue by daks-ua** [SimpleMobileTools/Simple-Dialer#724]
I get "No valid app found" when trying to add a contact. 
App version 5.18.1, installed from F-Droid, Android 13.

![Screenshot_2023-12-13-14-28-36-49_765f8dabff0c1b40e2676405b965e035~2](https://github.com/SimpleMobileTools/Simple-Dialer/assets/1014212/051252f2-140b-48a3-b83b-094060ad8a5c)

**Comment by daks-ua** [comment]
The issue fixed by installing Simple Contact Pro. Thanks!

**Comment by inson1** [comment]
@daks-ua
SMT apps were sold to ad company. https://github.com/SimpleMobileTools/General-Discussion/issues/241
Fork is here https://github.com/FossifyOrg
