### ISSUE TITLE
T9 Language support

### ISSUE THREAD

**Issue by Deldion** [SimpleMobileTools/Simple-Dialer#725]
It would be great to offer the ability to use T9 keyboard to search in alternative languages.

Example: While the app is able to be displayed in Greek, the T9 keyboard only searches in English.

**Comment by inson1** [comment]
@Deldion 
SMT apps were sold to ad company. https://github.com/SimpleMobileTools/General-Discussion/issues/241
Fork is here https://github.com/FossifyOrg

**Comment by Belyavin** [comment]
@Deldion I'm actually working on this right now for the fork. Please replicate the issue there and contact me about the details regarding Greek language.
