### ISSUE TITLE
Add more strings to localize

### ISSUE THREAD

**Issue by teemue** [SimpleMobileTools/Simple-Dialer#75]
There are few strings which have no tag in res/values so they could be localized, like these in the settings:
"Tab to open at app start" and it's options
"Change date and time format"

**Comment by tibbi** [comment]
strings reused by multiple apps are coming from Simple Commons, it mentioned at the bottom of every strings file. You can find them at https://github.com/SimpleMobileTools/Simple-Commons/tree/master/commons/src/main/res
