### ISSUE TITLE
When receiving calls, only sound plays.

### ISSUE THREAD

**Issue by Skaalgard** [SimpleMobileTools/Simple-Dialer#76]
I'm using a Nokia 2.3 with Android 10, and even though I have Dialer set as my default phone app, when I receive calls, nothing pops up. My ringtone activates, but I have to manually unlock my phone, open the dialer, and tell it to answer the call. This is rather annoying.. is there any way to fix this? I'm using the newest version of Simple-Dialer available through F-Droid.

**Comment by MorgothSauron** [comment]
I have the same problem on my Redmi Note 8 Pro. The phone ring as it should, but there is nothing on the screen to answer the call. Installed the app from F-Droid

**Comment by forkbomb9** [comment]
Same on a Nougat phone. But it works on two other phones, running 8.1 and 9

**Comment by pianoslum** [comment]
Same for Redmi Note 8T. This renders the app unusable unfortunately :/

**Comment by DigitalNXZ** [comment]
did ya guys tried to give the dialer the right permissions? like displaying on lockscreen etc? especially on Xiaomi phones it is a to do thing.

same goes with the simple clock app, as long it doesnt have the right permissions it only plays sound and do not show up!

there is alot of tricky stuff to do..

I hope I could help.

**Comment by tibbi** [comment]
if it will still happen in 5.7.+ try finding the app in your device settings and allow it appearing over other apps
