### ISSUE TITLE
Name of contact not shown on incoming calling and in call history

### ISSUE THREAD

**Issue by liborbednarik** [SimpleMobileTools/Simple-Dialer#77]
When a contact has more than one number, in my case tested with 2 and 3 numbers per contact, and he is calling me, his name is not shown, only phone number is shown. Then in history call, i do not see his name, just phone number. Applies and tested with several contacts. Dialer version 5.4.0, Android 7.1.2. When setting phone numbers of contact to same type (mobil), solved problem in call history in 4 cases, did not solve in 1 case.

**Comment by eengineer001** [comment]
Hello Simple Mobile Tools

I really appreciate the work you are doing. 

I do have the same bug as described by liborbednarik. Therefore, it would be absolute wonderful if you could fix this bug. Since it is really annoying.

Stay safe and healthy!

Your sincerely

eengineer001

**Comment by tibbi** [comment]
should be fixed in 5.5.1

**Comment by mosiser** [comment]
Sadly, it is still here.
Not in the incoming call screen, that works well.
Only in the history call list. If a contact have more than one number, only the number is shown, not the name.
Version 5.12.0 on Android 7

**Comment by liborbednarik** [comment]
Well,
I just stopped using the app because of this. This bug is a blocker for me. Sad enough. Wish author more energy and enthusiasm to improve his app.
Libor


9. května 2022 18:49:29 SELČ, mosiser ***@***.***> napsal:
>Sadly, it is still here.
>Not in the incoming call screen, that works well.
>Only in the history call list. If a contact have more than one number,
>only the number is shown, not the name.
>Version 5.12.0 on Android 7
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/SimpleMobileTools/Simple-Dialer/issues/77#issuecomment-1121339170
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

-- Sent from /e/ Mail.
