### ISSUE TITLE
Color of Dialer app icon does not change, crashes and leaves weird icon behind

### ISSUE THREAD

**Issue by liborbednarik** [SimpleMobileTools/Simple-Dialer#78]
When changing the app icon color, it does not change. The app then crashes and leaves weird icons behind. Restart of app does not help, restart of launcher does not help, restart of mobile does not help. Any ideas? Dialer version 5.4.0, Android 7.1.2., Bliss launcher version 1.3.2 (foundation.e.blisslauncher) Inside the Dialer app colors change beautifully. You have chosen very nice colors! 

![Screenshot_20200716-153924](https://user-images.githubusercontent.com/68383465/87682434-1c22b780-c780-11ea-997c-b7fabacef9d0.png)
![Screenshot_20200716-154056](https://user-images.githubusercontent.com/68383465/87682439-1cbb4e00-c780-11ea-97b6-d396aad135b1.png)
![Screenshot_20200716-154200](https://user-images.githubusercontent.com/68383465/87682444-1e851180-c780-11ea-9a45-b95fd22c2b36.png)

**Comment by tibbi** [comment]
it is described at clicking on the app icon color change for the first time. I guess you confirmed the dialog without actually reading it. Some launchers do not handle icon customization properly and just make the icon disappear. You should either change your launcher app, or just stick to the default orange icon.
