### ISSUE TITLE
[Feature request] Disable screen lock during call

### ISSUE THREAD

**Issue by danielmmmm** [SimpleMobileTools/Simple-Dialer#79]
I am unsure whether this is accomplished on an app level or done by the Android system. During a call, with screen switched off by the proximi sensor, the screen locks. To end a call, I have to unlock the screen, which is inconvenient and can lead to awkward situations when the counterpart expects me to hang up. I set my power button to end calls, but it does not seem to do so when the screen is locked.

My phone, F(x)tec Pro1, runs Android 9.

**Comment by genodeftest** [comment]
If this is being implemented, it should probably be optional. There are use cases where you want to lock the screen during call, e.g. if you are using the headset mode and walk away from your smartphone. If then some random person finds the smartphone, it should not be able to e.g. access you messages and e-mails.

**Comment by lfriese** [comment]
Is this already solved? I have a phone with a damaged proximity sensor, so my screen immediately locks as soon as I enter a call. But: I can easily end a call with my Power Button (I've also activated this option in the Android Settings)
My device locks after 2 minutes of inactivity, but the above works even with way longer phone calls.

I have a Nokia 8 Sirocco running Android 10.

**Comment by tibbi** [comment]
version 5.12.0 will have a snackbar at the bottom redirecting you to the Draw over other apps, check if that helps if enabled

**Comment by tibbi** [comment]
should work well already
