### ISSUE TITLE
Screen turns off during calls

### ISSUE THREAD

**Issue by pasdechance** [SimpleMobileTools/Simple-Dialer#80]
If I open the dialer and call someone my screen turns off until the call is over.

**Comment by tibbi** [comment]
does it happen only if you put something close to the top of the device? There is a sensor to avoid pressing something with your ear.

**Comment by pasdechance** [comment]
No. This happens every time since the last update. I haven't received a call today so I don't know what happens in that case.

**Comment by Saijin-Naib** [comment]
I also experience intermittent issues with this, especially if OpenCamera is opened on the lockscreen, or another "always alive" app like GPS/Nav (Magic Earth) is open in the background.

**Comment by pasdechance** [comment]
I am able to avoid this issue if I kill the other apps. OSMand~ is 100% guaranteed to lead to a black screen, for example.

**Comment by DSDV** [comment]
Can confirm latest fdroid and playstore version on latest LinageOS 17.1 with MIX2
Phone starts rining and as i pick it up the screen turns off ... so i have to turn it on click the awser button and the screens turns off again.

when i try to take notes during my call the screen turns off in seconds which is not a great experience :/

**Comment by DSDV** [comment]
any updates on this ?

**Comment by tibbi** [comment]
recheck with 5.7.0. If it still wont work, enable the app to be shown over other apps in the device settings
