### ISSUE TITLE
Block phone number by region or regex

### ISSUE THREAD

**Issue by rzafiamy** [SimpleMobileTools/Simple-Dialer#82]
Is it possible to extends the "blocked number feature" in dialer app with regex capabilities ?
Most people like me claim to be a victim of a "ping call" (receive a lot of unwanted calls from a bot number, the caller number changes every times but the country code is still the same ) .. It would be nice to have a feature in which we can block number using a regex (e.g: +322.* ).

**Comment by mareking** [comment]
I too would love to see this feature implemented!
There is in fact another FOSS app that already does this job nicely: NoPhoneSpam
It is also available on f-droid: https://f-droid.org/de/packages/at.bitfire.nophonespam/
And hosted on gitlab: https://gitlab.com/bitfireAT/NoPhoneSpam

@tibbi Maybe you can take a look at it and adopt some of its functionality and code.

**Comment by Naveen3Singh** [comment]
If anyone is willing to test and provide feedback, I have uploaded a [debug APK here](https://github.com/Naveen3Singh/Simple-Dialer/releases/download/test_call_blocking/dialer-fdroid-debug.apk)

or
 if you'd rather build an APK yourself, do it from [this branch](https://github.com/Naveen3Singh/Simple-Dialer/tree/blocking_calls)

**Rules (can change with feedback):**
'&ast;' works as the wildcard character. 
&ast;1919 blocks all numbers like xxxxxx1919 and +1242&ast; blocks all numbers like +1242xxxxxxx

**Comment by rzafiamy** [comment]
Thanks it is working ! I have just tested it. I noticed just that only a limited pattern can be used : use of *. Full regex is not supported (e.g.:  ^ , $ , [0-9]+,...)

I saw also that the blocked number does not appear in the history of call but if I remove it from the blocked number then it appears in again. For me , it could be interresting to see it in the call history even blocked.

**Comment by tibbi** [comment]
the initial implementation will be with asterisks yet, dont expect any advanced regexes yet.
