### ISSUE TITLE
all Groups are empty after first use

### ISSUE THREAD

**Issue by hype11** [SimpleMobileTools/Simple-Dialer#83]
all groups are empty when I open the app, do it in background and open it again.
If I close it in app overwiew and open it again. All things are fine till next open from background.

Version 5.4.1 over F-Droid
Android Version 9
Fairphone 3

**Comment by tibbi** [comment]
what groups you mean? There are no groups in Simple Dialer

**Comment by hype11** [comment]
I don't know how you call them. perhaps tabs.
contact tab, recent call overview and favourite contacts. All are empty.

**Comment by hype11** [comment]
if the tab is empty and I make a screenshot by android functionality, next time I activate the dialer app, the app refreshes its self and show all entries normally

**Comment by tibbi** [comment]
hm, dont you have similar issues with other apps? It is most likely some device specific issue.

**Comment by hype11** [comment]
no, nothing.
all other apps work normally, also yours (Gallery, File Manager ...)

**Comment by hype11** [comment]
is there any possibility to get debug logs or similar?

**Comment by tibbi** [comment]
not really, guess Ill keep an eye on it

**Comment by hype11** [comment]
The bug is gone after updating Android 9 to 10.
