### ISSUE TITLE
The name of the contact is not displayed when a call is received

### ISSUE THREAD

**Issue by tikitaka007** [SimpleMobileTools/Simple-Dialer#84]
The name of the contact is not displayed when a call is received
	
1) When a contact has more than one number and is stored in the phone's storage (Not visible to other applications) it is only displayed when the phone number is the first one in the list.

2) When a contact has some space in a phone number and is stored in the phone storage (Not visible for other applications)

This behavior does NOT occur when the numbers are stored in the main storage visible to other applications.

**Comment by tibbi** [comment]
what app version are you using? I mean version of both Simple Contacts Pro and Simple Dialer.

**Comment by tikitaka007** [comment]
> 
> 
> what app version are you using? I mean version of both Simple Contacts Pro and Simple Dialer.

Tested with:

Simple Contacts Pro v6.12.6 and v6.12.7
Simple Dialer v5.4.1

It is easy to reproduce the problem.

Save a contact with two phone numbers in the phone storage (Not visible for other applications)

Have them call you from those phones and you will check that if they call you the second number of the contact will not display the name and also if any number is saved with some space it will not display the name of the contact.

This behavior does NOT occur when numbers are stored in the main storage visible to other applications.

Android 9
Xiaomi

Thanks for taking the time to develop such useful software. Developing software requires a lot of time and dedication that is sometimes undervalued.

Thank you!

**Comment by bobweb01** [comment]
Hi there, I just wanted to chime in, that I have the same or similar problem. E. g. I see the name of a person in the SMS app, but in the dialer only the number, when a call is coming or in the recent list.
Dialer 5.5.0, Contacts 6.12.7 Pro, SMS 5.4.1 on Android 10, Motorola One Vision
Thanks!
