### ISSUE TITLE
Call time, mic and loudspeaker states on active call get reset when minimised

### ISSUE THREAD

**Issue by Wurzelmann** [SimpleMobileTools/Simple-Dialer#85]
Today I had to call my ISP and was stuck in the queue for ages, I then turned off the microphone, set the phone to loudspeaker and minimised the call in order to do different things in the meantime.

When I opened the call again, the call time had been reset and started from 0 again, the loudspeaker icon was in the wrong state (not activated), but it was active and the microphone icon had the same problem.

**Comment by tibbi** [comment]
cannot reproduce it anymore
