### ISSUE TITLE
Signal contacts are appearing twice

### ISSUE THREAD

**Issue by onnyyonn** [SimpleMobileTools/Simple-Dialer#87]
Contacts who have Signal installed are appearing twice in the dialer, even though they appear only once in Simple Contacts.

**Comment by billie80** [comment]
I also have duplicate entries, but there are only two of them. They are Signal contacts. However more than twenty which are also Signal contacts only show once.

**Comment by billie80** [comment]
It is related to Signal since when I remove the Signal account for synching, the duplicates are gone. After triggering a contact sync in Signal which recreates the account the duplicates appear again.

**Comment by tibbi** [comment]
recheck with 5.7.0 please, reopen if it is still broken
