### ISSUE TITLE
show more options at clicking a contact

### ISSUE THREAD

**Issue by qw123wh** [SimpleMobileTools/Simple-Dialer#9]
in the call log when you click on a contact do not call directly but show the possibility to send sms, call or show in the contacts or add to blacklist

**Comment by matejdro** [comment]
I think behavior should mimic the default phone app: tapping on the contact name should perform default action (call his default number or maybe event make it configurable), while tapping on contact's image should bring up other contact options.

**Comment by ltGuillaume** [comment]
@matejdro Agreed.

**Comment by Machion** [comment]
Also, when call log is set to grouping, tapping should unfold the whole log for this contact.

**Comment by JohnVeness** [comment]
Very much this. My instinct when clicking on a call log entry is that it should show more info on the call (dates, start/stop times, duration, which exact number, incoming or outgoing), with buttons to do other things. I *hate* it when I keep accidently ringing the person!

I would prefer this to happen when clicking anywhere on the call log entry, not just the avatar.

**Comment by danielmmmm** [comment]
I disagree to copying default phone app (which one, Google, Samsung, ...?).

Clicking on a name/number in the call log will start a call immediately. This can lead to very awkward situations (for people with social anxiety), when all I wanted to do was to copy the number or add  a number to my contacts.

We could have "call immediately" as the default behaviour, and a setting to change it. At the least, I would appreciate a safety pop-up asking me if I really want to make a call upon clicking onto a name/number.

**Comment by ltGuillaume** [comment]
Yeah, come to think of it, I tend to agree with @danielmmmm, it's very annoying that a tap will initiate a call right away.

**Comment by qw123wh** [comment]
we all agree on this issue. Also I think this and the #5 are fundamental in a dialer app. I'm sorry but for these two problems I can't use this app as default. These 2 are the most important problems. All the others are secondary

**Comment by tibbi** [comment]
some new top menu items will be added in 5.6.0

**Comment by Aga-C** [comment]
Are there still plans to add this feature? Current behavior in calls history is a bit annoying, because it is too easy to call someone by the mistake.
In my opinion, the best would be to add an alert box asking the user if he wants to make a call, like it is in the contact view.

**Comment by anandprajapati** [comment]
> in the call log when you click on a contact do not call directly but show the possibility to send sms, call or show in the contacts or add to blacklist

I agree..currently if a contact has 2 numbers the dialer pick one of then on its own and starts dialling. Ideally it should prompt the number to call or show both the numbers in the search result.

**Comment by Evidlo** [comment]
Here's a picture of the feature in question:

![Pictures_Screenshots_Screenshot_20220426-192733_Phone](https://user-images.githubusercontent.com/5455841/165415164-d135e970-f083-4d2d-ad6c-c56517b8cc0a.png)

**Comment by cenktaskin** [comment]
It would be really useful it can somehow involve social options (calling through Whatsapp or Telegram). There is an issue about this but the description is not clear enough #310 . 

More concretely, as a person who lives abroad I often use the aforementioned apps to contact people. I have to lead myself to the contact page and click from there. What would be really useful is to have a configuration option to have a preferred calling method, maybe in the beginning only which number to call, later if possible also the social options.
