### ISSUE TITLE
Search function has problem

### ISSUE THREAD

**Issue by jnezbeda** [SimpleMobileTools/Simple-Dialer#90]
Hi Tibor,
I am using [DAVx⁵ ](https://github.com/spmp/davx5), and I have 2 contacts with same name (father and son with of course different phone numbers). Search function is not working when I am typing: "Žáček" (in this moment I see 30 contacts which are completely wrong due to searching string). When I type "Žáček **J**" I get 3 contacts: 2 which I search for and 1 wrong.

I am using the latest version v5.5.0.

**Comment by tibbi** [comment]
is it related to the special characters with accents? Can you reproduce it with casual letters, like "John" or so?

**Comment by jnezbeda** [comment]
No, I think enconding is not the problem.
I think, that "John" is searched this way: contains "J", contains "O", contains "H", etc.

Example: man with name Abrahám, I am typing "abra", and your app found 2 results. Man with name Abrahám and man Ji**r**ásko J**a**ku**b** (bold for search string ABRA).

**Comment by tibbi** [comment]
retry with 5.5.1, reopen if it is still broken
