### ISSUE TITLE
Prioritize "more complete" matches in search

### ISSUE THREAD

**Issue by ltGuillaume** [SimpleMobileTools/Simple-Dialer#91]
When using the stock phone app, searching via T9 prioritizes "more complete" matches over alphabetic order. For example, if I type "mom", then the contact called "Mom" is at the top. In Simple Dialer, however, all contacts that match "mom" somewhere in the name are shown in alphabetic order. In this case, it means that the contact "Mom" doesn't even show up unless I scroll down first.

Could the search algorithm be improved to incorporate the Phone app's behavior?

**Comment by ltGuillaume** [comment]
Also, when I type in "Jac" for a name, even though there are names starting with "Jac", a lot of other entries are shown before (probably because of "522", but there is no way to open the contact entry from the dialer, so it's very annoying to check up on these things).

**Comment by bb1a2** [comment]
Unfortunately, this still doesn't work as desired!

Prioritize:
- complete first.
- Name match before (partial) number match.
- Favorites and recently called (in/out).
