### ISSUE TITLE
Caller History: No entry in case of suppressed caller ID / phone number

### ISSUE THREAD

**Issue by just-Nob** [SimpleMobileTools/Simple-Dialer#97]
# Environment:
* Simple Dialer Pro v.5.5.0
* taken from F-Droid repo
* hardware: BQ Aquaris X Pro
* OS: LineageOS 17.1 (Android 10)
* modding: root via Magisk, EdXPosed, some Magisk- & XPosed modules

# Description:
* Simple Dialer is currently running as standard phone app.
* If receiving a call without transmitted caller ID (= i.e. suppressed phone number), the call isn't displayed in the caller history. This is at least in case of a missed call, don't know if it's also the same on case of an answered call.
* That's it.

**Comment by tibbi** [comment]
should be showing as Unknown from 5.7.0
