### ISSUE TITLE
Calls not being logged under the "clock symbol"

### ISSUE THREAD

**Issue by meximan** [SimpleMobileTools/Simple-Dialer#99]
The simple dialer isn't logging incoming or outgoing calls under the "clock symbol in the dialer:  "no previous calls have been found".

**Comment by QuickJack** [comment]
I am using 5.5.1. Incoming as well as outgoing calls are logged and shown under the clock symbol as expected.

**Comment by tibbi** [comment]
calls will reset on resume starting from 5.6.0, guess thats what you meant
